// GENERATED by src/cli/genedkeys.ts from +Editor_Config.s and +Edit.s — do not edit.
//
// What a keystroke does, in three tables of 184 commands each. See
// ./keymap.ts for how they are walked; the shape is not obvious from the bytes.
//
// Copyright (c) 1992 Europress Software
// Copyright (c) 2020 Francois Lionet
// Published under the MIT licence as part of the official AMOS Professional
// source release.
const unhex = (s: string): Uint8Array => Uint8Array.from(s.match(/../g)!, (b) => parseInt(b, 16))

/**
 * `.Ed_KFonc` (+Editor_Config.s:283), $288 of the shipped
 * AMOSPro_Editor_Config: a VARIABLE-length list of two-byte {key, qualifiers}
 * records per command, each list closed by a zero byte, the whole table by
 * `$FF,0`. The assembler default gives every command exactly one record, so
 * the file reads as 184 groups of three, but Set Key Shortcut can put more
 * than one key on a command and the walk must not assume otherwise.
 */
export const ED_KFONC: Uint8Array = unhex(
  'cc0000cd0000cf0000ce0000cc0300cd0300cf0300ce0300cc0800cd0800cf0800ce0800bec3009ec300bec0009ec000' +
  'cc0b00cd0b000d0000c10000c60000510800590800c20000c20300c20800df0000c50000d90000c60800cc3000cd3000' +
  '4cc00053c30053c000c60300c1030048c000010000010000010000010000ad0b00ae0b00af0b00bd0b00be0b00bf0b00' +
  '8f08009d08009e08009f0800ad0800ae0800af0800bd0800be0800bf08004208004608004cc300430800500800c10800' +
  '55080046c0004ec00042c0000100004b0800010000530800010000010000d7000047c000d00000d10000d2000051c000' +
  '51c30001000049c0004dc0004dc300500b00d800000100004fc30043c300d50000d60000aec000550b0056c30043c000' +
  '410b00530b0046c3004ec30042c30001000057c3004bc0000100004d0800010000010000010000010000010000010000' +
  '01000054c300010000010000010000010000010000010000010000010000010000010000010000010000010000010000' +
  '01000001000001000001000001000001000055c00055c300010000010000010000010000010000010000010000010000' +
  'd3000050c00049c300010000010000010000010000010000010000010000010000010000010000010000010000010000' +
  '010000010000010000010000010000010000010000010000010000010000010000010000010000010000010000010000' +
  '010000010000010000010000410800010000d40000010000ff00',
)

/**
 * `FlagFonc` (+Edit.s:3347), $1FC0 of AMOSPro_Editor. One byte per command,
 * read by `Ed_FCall` (:2565) before the command runs. Bits, from the
 * assembler's own comment: 0 redraw the buffer, 1 redraw the line, 2 refuse
 * on a closed procedure, 5 allowed in a macro, 6 takes a command line,
 * 7 reachable from the ZAP remote control.
 */
export const FLAG_FONC: Uint8Array = unhex(
  'a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a3a5a5a6a6a5a5000000a2a5a0a0828280a4a400a0a0a0a0a0a0a0a0a0a0' +
  'a0a0a0a0a0a0a0a0a0a0a0a282a2a2a68180a0a1840086a00202208000000282800000a6a68002028202808080800000' +
  'a0a0a2828000800000000000000000000000000000000000000000000000000000000000000000000000000000000000' +
  '00800000000000c0c0c0000000000000000000000000000000000000000000000000000080c00000',
)

/**
 * `JFonc` (+Edit.s:3151), the routine each command branches to. Index 0 is
 * command 1: `Ed_FCall` takes a 0-based number and every comment in the
 * source numbers from 1.
 */
export const ED_ROUTINES: readonly string[] = [
  'Ed_CHaut', // 1  Cur Haut
  'Ed_CBas', // 2  Cur Bas
  'Ed_CGauche', // 3  Cur Gauche
  'Ed_CDroite', // 4  Cur Droite
  'Ed_HPage', // 5  Haut Page
  'Ed_BPage', // 6  Bas Page
  'Ed_MGauche', // 7  Mot gauche
  'Ed_MDroite', // 8  Mot Droite
  'Ed_PHaut', // 9  Page Haut
  'Ed_PBas', // 10 Page Bas
  'Ed_DLigne', // 11 Debut Ligne
  'Ed_FLigne', // 12 Fin Ligne
  'Ed_EtatUp', // 13 Bar Haut Haut
  'Ed_EtatDown', // 14 Bar haut Bas
  'Ed_BasUp', // 15 Bar Bas Haut
  'Ed_BasDown', // 16 Bar Bas Bas
  'Ed_HTexte', // 17 Haut Texte
  'Ed_BTexte', // 18 Bas Texte
  'Ed_Return', // 19 Return
  'Ed_Back', // 20 Backspace
  'Ed_Delete', // 21 Delete
  'Ed_EffLigne', // 22 Effacement Ligne
  'Ed_DelLiCu', // 23 Delete Ligne
  'Ed_Tab', // 24 Plus Tab
  'Ed_ShTab', // 25 Moins Tab
  'Ed_STab', // 26 Set Tab
  'Ed_UserMenu', // 27 Help
  'Ed_Escape', // 28 Escape
  'Ed_InsLine', // 29 Insert Ligne
  'Ed_DelFin', // 30 Delete Fin Ligne
  'Ed_PLabel', // 31 Previous Label
  'Ed_NLabel', // 32 Next Label
  'Ed_Load', // 33 Load
  'Ed_SaveAs', // 34 SaveAs
  'Ed_Save', // 35 Save
  'Ed_DelMot', // 36 Del Mot
  'Ed_BackMot', // 37 Back Mot
  'Ed_WindowHide', // 38 Hide Project
  'Ed_SMark0', // 39 Set Marks
  'Ed_SMark1',
  'Ed_SMark2',
  'Ed_SMark3',
  'Ed_SMark4',
  'Ed_SMark5',
  'Ed_SMark6',
  'Ed_SMark7',
  'Ed_SMark8',
  'Ed_SMark9',
  'Ed_GMark0', // 49 Goto Mark
  'Ed_GMark1',
  'Ed_GMark2',
  'Ed_GMark3',
  'Ed_GMark4',
  'Ed_GMark5',
  'Ed_GMark6',
  'Ed_GMark7',
  'Ed_GMark8',
  'Ed_GMark9',
  'Ed_BlocOn', // 59 Marche / Arret Bloc
  'Ed_BlocForget', // 60 Forget Bloc
  'Ed_OpenLoad', // 61 Open + Load
  'Ed_BlocCut', // 62 Cut Bloc
  'Ed_BlocPaste', // 63 Paste Bloc
  'Ed_DelDebut', // 64 Delete to S.O.L
  'Ed_Undo', // 65 Undo
  'Ed_Search', // 66 Search
  'Ed_SearchNext', // 67 Search Next
  'Ed_SearchPrev', // 68 Search Previous
  'EdZ_NewLine', // 69 ZAPPEUSE: replace line
  'Ed_RAlert', // 70 Recall last alert
  'EdZ_NewLineTok', // 71 ZAPPEUSE: replace+tokenise
  'Ed_BlocStore', // 72 Store bloc
  'Ed_Key2Menu', // 73 Set Key Shortcut
  'Ed_Prg2Menu', // 74 Affect Program to menu
  'Ed_Ins', // 75 Flip Insert Mode
  'Ed_GotoL', // 76 Goto Line Number
  'Ed_Run', // 77 Run
  'Ed_Test', // 78 Test
  'Ed_Indent', // 79 Indent
  'Ed_New', // 80 Clear
  'Ed_CloseWindowQuit', // 81 Close
  'Ed_Quit', // 82 Quit
  'Ed_Infos', // 83 Editor Informations
  'Ed_Merge', // 84 Merge
  'Ed_LoadA', // 85 Merge Ascii
  'Ed_BlocPrint', // 86 Print Bloc
  'Ed_ProcOpen', // 87 Open / Close
  'Ed_LoadHidden', // 88 Load Hidden program
  'Ed_ProcsOpen', // 89 Open All
  'Ed_ProcsClose', // 90 Close All
  'Ed_PrevWindow', // 91 Previous Window
  'Ed_NextWindow', // 92 Next Window
  'Ed_FlipSizeWindow', // 93 Enlarge Window
  'Ed_Redo', // 94 Redo
  'Ed_SplitWindow', // 95 Split View
  'Ed_LinkCursor', // 96 Link Cursor
  'Ed_BlocSaveAscii', // 97 Save Block as Ascii
  'Ed_BlocSave', // 98 Save Block
  'Ed_Replace', // 99 Replace New
  'Ed_ReplaceNext', // 100 Replace Next
  'Ed_ReplacePrev', // 101 Replace Previous
  'Ed_NewAllHidden', // 102 New All Hidden Programs
  'Ed_OpenWindow', // 103 Open New
  'Ed_ShowKey', // 104 Show Key shortcuts
  'Ed_Wb', // 105 Workbench
  'EdMa_New', // 106 Set new Macro
  'EdMa_Del', // 107 Clear One Macro
  'EdMa_DelAll', // 108 Clear All Macros
  'EdMa_LoadAs', // 109 Load Macros
  'EdMa_SaveAs', // 110 Save Macros
  'Ed_RunHidden', // 111 Run
  'Ed_EditHidden', // 112 Edit
  'Ed_NewHidden', // 113 New
  'Ed_SetBuffer', // 114 Set Buffer
  'Ed_UserMenu', // 0
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 5
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 10
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 15
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_AddUser', // 135 Add user option
  'Ed_DelUser', // 136 Del user option
  'EdC_SaveDefault', // 137 Save default config
  'EdC_SaveAs', // 138 Save As
  'EdC_LoadDefault', // 139 Load default config
  'EdC_LoadAs', // 140 Load As
  'Ed_QuitOptions', // 141 Quit Options
  'Ed_SetAutoSave', // 142 Autosave
  'EdMa_LoadDefault', // 143 Load Default Macros
  'EdMa_SaveDefault', // 144 Save Default Macros
  'Ed_GoMonitor', // 145 Monitor
  'Ed_PrgPrint', // 146 Program Print
  'Ed_Check1.3', // 147 Check 1.3
  'Ed_SamOn', // 148 Sound On / Off
  'Ed_AboutExt', // 149 About extensions
  'Ed_About', // 150 About AMOS
  'Ed_ProcML', // 151 Insert machine langage
  'Ed_SaveAsName', // 152 Sauve sans changer nom
  'Ed_CloseName', // 153 Ferme une fenetre nom
  'Ed_Rename', // 154 Rename le programme courant
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 157
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 162
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 167
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu',
  'Ed_UserMenu', // 172 Interpretor Setup
  'Ed_UserMenu', // 173 Editor Setup
  'Ed_UserMenu', // 174 Editor Menus
  'Ed_UserMenu', // 175 Editor Dialogs
  'Ed_UserMenu', // 176 Test-Time
  'Ed_UserMenu', // 177 Run-Time
  'Ed_UserMenu', // 178 Colour Palette
  'EdM_PrevHidden', // 179 Previous programs
  'EdM_NextHidden', // 180 Next programs
  'Ed_BlocAll', // 181 All text as block
  'EdZ_NewConfig', // 182 ZAP: remplace chaine dans config
  'Ed_GoHelp', // 183 Branche au HELP
  'Ed_UserMenu', // 184
]
