// GENERATED by src/cli/gencycles.ts from the AMOS Pro 2.00 assembler sources — do not edit.
// 68000 cycles for the routine behind each core token, on an uncontended bus.

export interface TokenCycles {
  /** cycles for the instruction form, null when the token has none */
  instr: number | null
  /** cycles for the function form */
  func: number | null
  /** the routine loops over its data, so the figure is a floor */
  loops: boolean
}

/** Keyed by token id: the byte offset of the entry in the library token table. */
export const TOKEN_CYCLES: Record<number, TokenCycles> = {
  0: { instr: null, func: 40, loops: false },
  6: { instr: 286, func: 260, loops: true },
  12: { instr: 44, func: null, loops: false },
  18: { instr: 2238, func: null, loops: true },
  24: { instr: 52, func: null, loops: false },
  30: { instr: null, func: 32, loops: false },
  38: { instr: null, func: 78, loops: true },
  46: { instr: null, func: 78, loops: true },
  54: { instr: null, func: 32, loops: false },
  62: { instr: null, func: 32, loops: false },
  70: { instr: null, func: 52, loops: true },
  78: { instr: 118, func: 118, loops: true },
  84: { instr: 16, func: 40, loops: false }, // :
  92: { instr: null, func: 40, loops: false }, // ,
  100: { instr: null, func: null, loops: false }, // ;
  108: { instr: null, func: null, loops: false }, // #
  116: { instr: null, func: 78, loops: true }, // (
  124: { instr: null, func: 40, loops: false }, // )
  132: { instr: null, func: 78, loops: true }, // [
  140: { instr: null, func: null, loops: false }, // ]
  148: { instr: null, func: 40, loops: false }, // to
  156: { instr: null, func: 222, loops: true }, // not
  166: { instr: 672, func: null, loops: true }, // swap
  176: { instr: 306, func: null, loops: false }, // def fn
  188: { instr: null, func: 810, loops: true }, // fn
  196: { instr: 26, func: null, loops: false }, // follow off
  212: { instr: 26, func: null, loops: false }, // follow
  224: { instr: 90, func: null, loops: true }, // resume next
  242: { instr: null, func: 266, loops: false }, // inkey$
  254: { instr: null, func: 470, loops: true }, // repeat$
  270: { instr: null, func: 470, loops: true }, // zone$
  284: { instr: null, func: 470, loops: true }, // border$
  300: { instr: 264, func: null, loops: false }, // double buffer
  320: { instr: null, func: 172, loops: false }, // start
  332: { instr: null, func: 240, loops: true }, // length
  346: { instr: 54, func: null, loops: true }, // doke
  360: { instr: 230, func: null, loops: false }, // on menu del
  378: { instr: 52, func: null, loops: true }, // on menu on
  394: { instr: 52, func: null, loops: true }, // on menu off
  412: { instr: 32, func: null, loops: false }, // every on
  426: { instr: 32, func: null, loops: false }, // every off
  442: { instr: null, func: 104, loops: false }, // logbase
  456: { instr: null, func: 32, loops: false }, // !logic
  468: { instr: null, func: 36, loops: false },
  476: { instr: null, func: 52, loops: true }, // asc
  486: { instr: 26, func: 26, loops: false }, // as
  494: { instr: 578, func: null, loops: true }, // call
  504: { instr: null, func: 324, loops: false }, // execall
  518: { instr: null, func: 320, loops: false }, // gfxcall
  532: { instr: null, func: 320, loops: false }, // doscall
  546: { instr: null, func: 320, loops: false }, // intcall
  560: { instr: 160, func: null, loops: false }, // freeze
  572: { instr: 804, func: null, loops: true }, // for
  582: { instr: 152, func: null, loops: true }, // next
  592: { instr: 122, func: null, loops: true }, // repeat
  604: { instr: 210, func: null, loops: true }, // until
  616: { instr: 90, func: null, loops: true }, // while
  628: { instr: 238, func: null, loops: true }, // wend
  638: { instr: 132, func: null, loops: true }, // do
  646: { instr: 52, func: null, loops: true }, // loop
  656: { instr: 304, func: null, loops: true }, // exit if
  670: { instr: 88, func: null, loops: true }, // exit
  680: { instr: 274, func: null, loops: true }, // goto
  690: { instr: 266, func: null, loops: true }, // gosub
  702: { instr: 252, func: null, loops: true }, // if
  710: { instr: null, func: 40, loops: false }, // then
  720: { instr: 164, func: 32, loops: true }, // else
  730: { instr: 16, func: 40, loops: false }, // end if
  742: { instr: 36, func: null, loops: true }, // on error
  756: { instr: 196, func: null, loops: false }, // on break proc
  776: { instr: 1508, func: null, loops: true }, // on menu
  790: { instr: 666, func: null, loops: true }, // on
  798: { instr: 138, func: null, loops: true }, // resume label
  816: { instr: 90, func: null, loops: true }, // resume
  828: { instr: 56, func: null, loops: true }, // pop proc
  842: { instr: 434, func: null, loops: false }, // every
  854: { instr: 26, func: null, loops: false }, // step
  864: { instr: 86, func: null, loops: true }, // return
  876: { instr: 86, func: null, loops: true }, // pop
  886: { instr: 40, func: null, loops: false }, // procedure
  902: { instr: 2256, func: null, loops: true }, // proc
  912: { instr: 172, func: null, loops: true }, // end proc
  926: { instr: 100, func: null, loops: true }, // shared
  938: { instr: 100, func: null, loops: true }, // global
  950: { instr: 14, func: null, loops: false }, // end
  960: { instr: 26, func: null, loops: false }, // stop
  970: { instr: null, func: 36, loops: false }, // param#
  982: { instr: null, func: 36, loops: false }, // param$
  994: { instr: null, func: 36, loops: false }, // param
  1006: { instr: 0, func: null, loops: true }, // error
  1018: { instr: null, func: 48, loops: true }, // errn
  1028: { instr: 60, func: null, loops: false }, // data
  1038: { instr: 328, func: null, loops: true }, // read
  1048: { instr: 166, func: null, loops: true }, // restore
  1062: { instr: 32, func: null, loops: false }, // break off
  1078: { instr: 56, func: null, loops: false }, // break on
  1092: { instr: 270, func: null, loops: false }, // inc
  1102: { instr: 270, func: null, loops: false }, // dec
  1112: { instr: 336, func: null, loops: false }, // !add
  1122: { instr: 620, func: null, loops: true },
  1130: { instr: 446, func: null, loops: false }, // print #
  1142: { instr: 414, func: null, loops: true }, // print
  1154: { instr: 50, func: null, loops: false }, // lprint
  1166: { instr: null, func: 944, loops: true }, // !input$
  1180: { instr: null, func: 476, loops: true },
  1190: { instr: 26, func: 26, loops: false }, // using
  1202: { instr: 14270, func: null, loops: true }, // input #
  1214: { instr: 30, func: null, loops: false }, // line input #
  1232: { instr: 30, func: null, loops: false }, // input
  1244: { instr: 16098, func: null, loops: true }, // line input
  1260: { instr: 32, func: null, loops: false }, // !run
  1270: { instr: 36, func: null, loops: true },
  1278: { instr: 16, func: null, loops: false }, // set buffer
  1294: { instr: 1370, func: null, loops: true }, // !mid$
  1310: { instr: 1188, func: null, loops: true },
  1320: { instr: 1180, func: null, loops: true }, // left$
  1334: { instr: 1216, func: null, loops: true }, // right$
  1350: { instr: null, func: 58, loops: true }, // flip$
  1362: { instr: null, func: 204, loops: false }, // chr$
  1374: { instr: null, func: 226, loops: true }, // space$
  1388: { instr: null, func: 250, loops: true }, // string$
  1404: { instr: null, func: 66, loops: true }, // upper$
  1418: { instr: null, func: 66, loops: true }, // lower$
  1432: { instr: null, func: 306, loops: true }, // str$
  1444: { instr: null, func: 366, loops: true }, // val
  1454: { instr: null, func: 458, loops: true }, // !bin$
  1466: { instr: null, func: 466, loops: true },
  1476: { instr: null, func: 458, loops: true }, // !hex$
  1488: { instr: null, func: 466, loops: true },
  1498: { instr: null, func: 36, loops: false }, // len
  1508: { instr: null, func: 240, loops: false }, // !instr
  1524: { instr: null, func: 260, loops: false },
  1536: { instr: null, func: 188, loops: false }, // tab$
  1546: { instr: null, func: 1424, loops: false }, // free
  1556: { instr: null, func: 290, loops: true }, // varptr
  1568: { instr: 1012, func: null, loops: false }, // remember x
  1584: { instr: 1012, func: null, loops: false }, // remember y
  1600: { instr: 112, func: null, loops: true }, // dim
  1610: { instr: 24, func: null, loops: false }, // rem
  1618: { instr: 24, func: null, loops: false }, // '
  1624: { instr: 330, func: null, loops: true }, // sort
  1634: { instr: null, func: 366, loops: true }, // match
  1648: { instr: 18, func: null, loops: false }, // edit
  1658: { instr: 18, func: null, loops: false }, // direct
  1670: { instr: null, func: 48, loops: true }, // rnd
  1680: { instr: 32, func: null, loops: false }, // randomize
  1696: { instr: null, func: 38, loops: false }, // sgn
  1706: { instr: null, func: 34, loops: true }, // abs
  1716: { instr: null, func: 16, loops: false }, // int
  1726: { instr: 32, func: null, loops: false }, // radian
  1738: { instr: 32, func: null, loops: false }, // degree
  1750: { instr: null, func: 52, loops: false }, // pi#
  1760: { instr: 82, func: null, loops: true }, // fix
  1770: { instr: null, func: 382, loops: true }, // min
  1782: { instr: null, func: 424, loops: true }, // max
  1794: { instr: null, func: 90, loops: false }, // sin
  1804: { instr: null, func: 90, loops: false }, // cos
  1814: { instr: null, func: 90, loops: false }, // tan
  1824: { instr: null, func: 198, loops: true }, // asin
  1836: { instr: null, func: 198, loops: true }, // acos
  1848: { instr: null, func: 198, loops: true }, // atan
  1860: { instr: null, func: 90, loops: false }, // hsin
  1872: { instr: null, func: 90, loops: false }, // hcos
  1884: { instr: null, func: 90, loops: false }, // htan
  1896: { instr: null, func: 144, loops: false }, // sqr
  1906: { instr: null, func: 144, loops: false }, // log
  1916: { instr: null, func: 144, loops: false }, // ln
  1926: { instr: null, func: 90, loops: false }, // exp
  1936: { instr: 3424, func: null, loops: false }, // menu to bank
  1956: { instr: 1890, func: null, loops: false }, // bank to menu
  1976: { instr: 80, func: null, loops: true }, // menu on
  1990: { instr: 32, func: null, loops: false }, // menu off
  2004: { instr: 6580, func: null, loops: false }, // menu calc
  2020: { instr: 32, func: null, loops: false }, // menu mouse on
  2040: { instr: 32, func: null, loops: false }, // menu mouse off
  2060: { instr: 164, func: null, loops: true }, // menu base
  2078: { instr: 744, func: null, loops: true }, // set menu
  2098: { instr: null, func: 294, loops: false }, // x menu
  2112: { instr: null, func: 294, loops: false }, // y menu
  2126: { instr: 782, func: null, loops: true }, // menu key
  2146: { instr: 286, func: null, loops: false }, // menu bar
  2162: { instr: 298, func: null, loops: false }, // menu line
  2178: { instr: 298, func: null, loops: false }, // menu tline
  2196: { instr: 286, func: null, loops: false }, // menu movable
  2216: { instr: 286, func: null, loops: false }, // menu static
  2234: { instr: 286, func: null, loops: false }, // menu item movable
  2258: { instr: 286, func: null, loops: false }, // menu item static
  2282: { instr: 286, func: null, loops: false }, // menu active
  2300: { instr: 286, func: null, loops: false }, // menu inactive
  2320: { instr: 286, func: null, loops: false }, // menu separate
  2340: { instr: 286, func: null, loops: false }, // menu link
  2356: { instr: 290, func: null, loops: false }, // menu called
  2374: { instr: 290, func: null, loops: false }, // menu once
  2390: { instr: 434, func: null, loops: true }, // menu del
  2404: { instr: 1970, func: null, loops: true }, // menu$
  2416: { instr: null, func: 52, loops: false }, // !choice
  2430: { instr: null, func: 94, loops: false },
  2438: { instr: 782, func: null, loops: false }, // !screen copy
  2460: { instr: 748, func: null, loops: false },
  2472: { instr: 846, func: null, loops: false },
  2494: { instr: 812, func: null, loops: false },
  2518: { instr: 556, func: null, loops: false }, // screen clone
  2538: { instr: 176, func: null, loops: true }, // screen open
  2564: { instr: 494, func: null, loops: true }, // screen close
  2584: { instr: 418, func: null, loops: false }, // screen display
  2614: { instr: 308, func: null, loops: false }, // screen offset
  2638: { instr: 26, func: 26, loops: false }, // screen size
  2654: { instr: null, func: 134, loops: true }, // screen colour
  2674: { instr: 300, func: null, loops: false }, // !screen to front
  2696: { instr: 258, func: null, loops: false },
  2704: { instr: 412, func: null, loops: false }, // !screen to back
  2726: { instr: 370, func: null, loops: false },
  2734: { instr: 320, func: null, loops: false }, // !screen hide
  2752: { instr: 278, func: null, loops: false },
  2760: { instr: 320, func: null, loops: false }, // !screen show
  2778: { instr: 278, func: null, loops: false },
  2786: { instr: 432, func: null, loops: false }, // !screen swap
  2804: { instr: 370, func: null, loops: false },
  2812: { instr: 940, func: null, loops: true }, // !save iff
  2828: { instr: 914, func: null, loops: true },
  2838: { instr: 456, func: null, loops: false }, // view
  2848: { instr: 32, func: null, loops: false }, // auto view off
  2868: { instr: 32, func: null, loops: false }, // auto view on
  2886: { instr: null, func: 90, loops: false }, // screen base
  2904: { instr: null, func: 102, loops: false }, // !screen width
  2924: { instr: null, func: 222, loops: false },
  2932: { instr: null, func: 102, loops: false }, // !screen height
  2952: { instr: null, func: 222, loops: false },
  2960: { instr: 732, func: null, loops: false }, // !get palette
  2980: { instr: 706, func: null, loops: false },
  2990: { instr: 632, func: null, loops: false }, // !cls
  3000: { instr: 3722, func: null, loops: false },
  3008: { instr: 3750, func: null, loops: false },
  3024: { instr: 414, func: null, loops: false }, // def scroll
  3054: { instr: null, func: 316, loops: false }, // !x hard
  3068: { instr: null, func: 304, loops: false },
  3078: { instr: null, func: 316, loops: false }, // !y hard
  3092: { instr: null, func: 308, loops: false },
  3102: { instr: null, func: 340, loops: false }, // !x screen
  3118: { instr: null, func: 332, loops: false },
  3128: { instr: null, func: 340, loops: false }, // !y screen
  3144: { instr: null, func: 332, loops: false },
  3154: { instr: null, func: 338, loops: false }, // x text
  3168: { instr: null, func: 338, loops: false }, // y text
  3182: { instr: 492, func: null, loops: false }, // !screen
  3196: { instr: null, func: 40, loops: false },
  3204: { instr: null, func: 32, loops: false }, // hires
  3216: { instr: null, func: 24, loops: false }, // lowres
  3228: { instr: 400, func: null, loops: false }, // dual playfield
  3252: { instr: 400, func: null, loops: false }, // dual priority
  3274: { instr: 182, func: null, loops: false }, // wait vbl
  3288: { instr: 382, func: null, loops: false }, // default palette
  3310: { instr: 4868, func: null, loops: false }, // default
  3324: { instr: 750, func: null, loops: true }, // palette
  3338: { instr: 120, func: null, loops: false }, // colour back
  3356: { instr: 294, func: null, loops: false }, // !colour
  3372: { instr: null, func: 186, loops: false },
  3380: { instr: 460, func: null, loops: false }, // flash off
  3396: { instr: 534, func: null, loops: false }, // flash
  3410: { instr: 186, func: null, loops: false }, // shift off
  3426: { instr: 566, func: null, loops: true }, // shift up
  3448: { instr: 566, func: null, loops: true }, // shift down
  3472: { instr: 596, func: null, loops: false }, // !set rainbow
  3502: { instr: 570, func: null, loops: false },
  3522: { instr: 272, func: null, loops: false }, // !rainbow del
  3540: { instr: 258, func: null, loops: false },
  3548: { instr: 198, func: null, loops: false }, // rainbow
  3568: { instr: 198, func: 190, loops: false }, // rain
  3582: { instr: 258, func: null, loops: true }, // fade
  3592: { instr: null, func: 104, loops: false }, // phybase
  3606: { instr: null, func: 24, loops: false }, // !physic
  3620: { instr: null, func: 36, loops: false },
  3628: { instr: 88, func: null, loops: false }, // autoback
  3644: { instr: 360, func: null, loops: false }, // !plot
  3658: { instr: 452, func: null, loops: true },
  3670: { instr: null, func: 340, loops: false }, // point
  3684: { instr: 230, func: null, loops: false }, // draw to
  3700: { instr: 364, func: null, loops: false }, // draw
  3718: { instr: 442, func: null, loops: false }, // ellipse
  3738: { instr: 462, func: null, loops: false }, // circle
  3756: { instr: 126, func: null, loops: true }, // polyline
  3770: { instr: 170, func: null, loops: true }, // polygon
  3784: { instr: 330, func: null, loops: false }, // bar
  3800: { instr: 406, func: null, loops: true }, // box
  3816: { instr: 2300, func: null, loops: false }, // !paint
  3832: { instr: 2274, func: null, loops: false },
  3844: { instr: 178, func: null, loops: false }, // gr locate
  3862: { instr: null, func: 196, loops: false }, // text length
  3880: { instr: null, func: 76, loops: false }, // text styles
  3898: { instr: null, func: 76, loops: false }, // text base
  3914: { instr: 388, func: null, loops: true }, // text
  3930: { instr: 68, func: null, loops: false }, // set text
  3946: { instr: 108, func: null, loops: true }, // set paint
  3962: { instr: 476, func: null, loops: false }, // get fonts
  3978: { instr: 476, func: null, loops: false }, // get disc fonts
  3998: { instr: 476, func: null, loops: false }, // get rom fonts
  4018: { instr: 648, func: null, loops: false }, // set font
  4034: { instr: null, func: 284, loops: true }, // font$
  4046: { instr: 6302, func: null, loops: false }, // hslider
  4072: { instr: 5164, func: null, loops: false }, // vslider
  4098: { instr: 592, func: null, loops: false }, // set slider
  4130: { instr: 872, func: null, loops: false }, // set pattern
  4148: { instr: 68, func: null, loops: false }, // set line
  4164: { instr: 218, func: null, loops: true }, // !ink
  4176: { instr: 206, func: null, loops: true },
  4186: { instr: 172, func: null, loops: true },
  4198: { instr: 76, func: null, loops: false }, // gr writing
  4216: { instr: 178, func: null, loops: false }, // !clip
  4228: { instr: 214, func: null, loops: false },
  4242: { instr: 40, func: null, loops: false }, // !set tempras
  4260: { instr: 118, func: null, loops: false },
  4268: { instr: 350, func: null, loops: false },
  4278: { instr: 846, func: null, loops: true }, // !appear
  4296: { instr: 820, func: null, loops: true },
  4310: { instr: 2762, func: null, loops: true }, // zoom
  4340: { instr: 1288, func: null, loops: false }, // get cblock
  4366: { instr: 700, func: null, loops: false }, // !put cblock
  4384: { instr: 662, func: null, loops: false },
  4396: { instr: 514, func: null, loops: false }, // !del cblock
  4414: { instr: 632, func: null, loops: false },
  4422: { instr: 398, func: null, loops: false }, // !get block
  4448: { instr: 372, func: null, loops: false },
  4466: { instr: 610, func: null, loops: false }, // !put block
  4484: { instr: 586, func: null, loops: false },
  4496: { instr: 574, func: null, loops: false },
  4510: { instr: 540, func: null, loops: false },
  4526: { instr: 1354, func: null, loops: false }, // !del block
  4542: { instr: 262, func: null, loops: false },
  4550: { instr: 1510, func: null, loops: false }, // key speed
  4568: { instr: null, func: 200, loops: false }, // key state
  4584: { instr: null, func: 108, loops: false }, // key shift
  4600: { instr: null, func: 288, loops: false }, // joy
  4610: { instr: null, func: 338, loops: false }, // jup
  4620: { instr: null, func: 338, loops: false }, // jdown
  4632: { instr: null, func: 338, loops: false }, // jleft
  4644: { instr: null, func: 338, loops: false }, // jright
  4658: { instr: null, func: 338, loops: false }, // fire
  4670: { instr: null, func: 24, loops: false }, // true
  4680: { instr: null, func: 24, loops: false }, // false
  4692: { instr: 506, func: null, loops: false }, // put key
  4706: { instr: null, func: 52, loops: false }, // scancode
  4720: { instr: null, func: 52, loops: false }, // scanshift
  4736: { instr: 120, func: null, loops: false }, // clear key
  4752: { instr: 486, func: null, loops: true }, // wait key
  4766: { instr: 222, func: null, loops: true }, // wait
  4778: { instr: 494, func: 182, loops: true }, // key$
  4790: { instr: null, func: 292, loops: false }, // !scan$
  4804: { instr: null, func: 266, loops: false },
  4814: { instr: 32, func: 36, loops: false }, // timer
  4826: { instr: 1500, func: null, loops: false }, // !wind open
  4852: { instr: 1488, func: null, loops: false },
  4870: { instr: 1462, func: null, loops: false },
  4890: { instr: 172, func: null, loops: false }, // wind close
  4906: { instr: 64, func: null, loops: false }, // wind save
  4922: { instr: 318, func: null, loops: false }, // wind move
  4940: { instr: 454, func: null, loops: false }, // wind size
  4958: { instr: 382, func: null, loops: false }, // window
  4972: { instr: null, func: 164, loops: false }, // windon
  4984: { instr: 1050, func: null, loops: false }, // locate
  5000: { instr: 1012, func: null, loops: false }, // clw
  5010: { instr: 1012, func: null, loops: false }, // home
  5020: { instr: 1042, func: null, loops: false }, // curs pen
  5036: { instr: null, func: 244, loops: false }, // pen$
  5048: { instr: null, func: 244, loops: false }, // paper$
  5062: { instr: null, func: 222, loops: true }, // at
  5074: { instr: 1042, func: null, loops: false }, // pen
  5084: { instr: 1042, func: null, loops: false }, // paper
  5096: { instr: 1232, func: null, loops: false }, // centre
  5110: { instr: 332, func: null, loops: false }, // border
  5128: { instr: 1146, func: null, loops: false }, // !writing
  5144: { instr: 1120, func: null, loops: false },
  5154: { instr: 876, func: null, loops: false }, // title top
  5170: { instr: 876, func: null, loops: false }, // title bottom
  5190: { instr: 1012, func: null, loops: false }, // curs off
  5204: { instr: 1012, func: null, loops: false }, // curs on
  5218: { instr: 1012, func: null, loops: false }, // inverse off
  5236: { instr: 1012, func: null, loops: false }, // inverse on
  5252: { instr: 1012, func: null, loops: false }, // under off
  5268: { instr: 1012, func: null, loops: false }, // under on
  5282: { instr: 1012, func: null, loops: false }, // shade off
  5298: { instr: 1012, func: null, loops: false }, // shade on
  5312: { instr: 1012, func: null, loops: false }, // scroll off
  5328: { instr: 1012, func: null, loops: false }, // scroll on
  5344: { instr: 600, func: null, loops: true }, // scroll
  5358: { instr: null, func: 188, loops: false }, // cup$
  5368: { instr: null, func: 188, loops: false }, // cdown$
  5380: { instr: null, func: 188, loops: false }, // cleft$
  5392: { instr: null, func: 188, loops: false }, // cright$
  5406: { instr: 1012, func: null, loops: false }, // cup
  5416: { instr: 1012, func: null, loops: false }, // cdown
  5428: { instr: 1012, func: null, loops: false }, // cleft
  5440: { instr: 1012, func: null, loops: false }, // cright
  5452: { instr: 1012, func: null, loops: false }, // memorize x
  5468: { instr: 1012, func: null, loops: false }, // memorize y
  5484: { instr: null, func: 298, loops: true }, // cmove$
  5500: { instr: 1196, func: null, loops: true }, // cmove
  5514: { instr: 1012, func: null, loops: false }, // !cline
  5526: { instr: 1076, func: null, loops: false },
  5534: { instr: 100, func: null, loops: true }, // hscroll
  5548: { instr: 100, func: null, loops: true }, // vscroll
  5562: { instr: 1060, func: null, loops: false }, // set tab
  5576: { instr: 1138, func: null, loops: true }, // set curs
  5606: { instr: null, func: 192, loops: false }, // x curs
  5618: { instr: null, func: 192, loops: false }, // y curs
  5630: { instr: null, func: 212, loops: false }, // x graphic
  5646: { instr: null, func: 212, loops: false }, // y graphic
  5662: { instr: null, func: 76, loops: false }, // xgr
  5672: { instr: null, func: 76, loops: false }, // ygr
  5682: { instr: 1412, func: null, loops: false }, // !reserve zone
  5702: { instr: 1398, func: null, loops: false },
  5710: { instr: 188, func: null, loops: true }, // !reset zone
  5728: { instr: 174, func: null, loops: true },
  5736: { instr: 226, func: null, loops: false }, // set zone
  5760: { instr: null, func: 502, loops: false }, // !zone
  5774: { instr: null, func: 510, loops: false },
  5786: { instr: null, func: 722, loops: false }, // !hzone
  5802: { instr: null, func: 730, loops: false },
  5814: { instr: null, func: 498, loops: false }, // !scin
  5828: { instr: null, func: 506, loops: false },
  5840: { instr: null, func: 552, loops: false }, // mouse screen
  5858: { instr: null, func: 772, loops: false }, // mouse zone
  5874: { instr: 94, func: null, loops: false }, // set input
  5892: { instr: 218, func: null, loops: true }, // close workbench
  5914: { instr: 0, func: null, loops: false }, // close editor
  5932: { instr: null, func: 4580, loops: true }, // dir first$
  5950: { instr: null, func: 976, loops: true }, // dir next$
  5966: { instr: null, func: 46, loops: false }, // exist
  5978: { instr: 862, func: 364, loops: true }, // dir$
  5990: { instr: 5124, func: null, loops: true }, // !ldir/w
  6004: { instr: 5200, func: null, loops: true },
  6012: { instr: 5124, func: null, loops: true }, // !dir/w
  6024: { instr: 5200, func: null, loops: true },
  6032: { instr: 5080, func: null, loops: true }, // !ldir
  6044: { instr: 5156, func: null, loops: true },
  6052: { instr: 5080, func: null, loops: true }, // !dir
  6062: { instr: 5156, func: null, loops: true },
  6070: { instr: 108, func: null, loops: true }, // set dir
  6084: { instr: 318, func: null, loops: true }, // set dir
  6100: { instr: 962, func: null, loops: true }, // !load iff
  6116: { instr: 928, func: null, loops: true },
  6126: { instr: 32, func: null, loops: false }, // mask iff
  6142: { instr: null, func: 24, loops: false }, // picture
  6156: { instr: 1088, func: null, loops: true }, // bload
  6170: { instr: 1156, func: null, loops: true }, // bsave
  6186: { instr: 924, func: null, loops: true }, // pload
  6200: { instr: 846, func: null, loops: true }, // !save
  6212: { instr: 854, func: null, loops: true },
  6222: { instr: 888, func: null, loops: true }, // !load
  6234: { instr: 892, func: null, loops: true },
  6244: { instr: null, func: 600, loops: true }, // dfree
  6256: { instr: 744, func: null, loops: true }, // mkdir
  6268: { instr: null, func: 322, loops: false }, // lof
  6278: { instr: null, func: 344, loops: false }, // eof
  6288: { instr: 322, func: 294, loops: true }, // pof
  6300: { instr: null, func: 270, loops: true }, // port
  6312: { instr: 1068, func: null, loops: false }, // open random
  6332: { instr: 1028, func: null, loops: true }, // open in
  6348: { instr: 1028, func: null, loops: true }, // open out
  6366: { instr: 1028, func: null, loops: true }, // open port
  6384: { instr: 1080, func: null, loops: false }, // append
  6400: { instr: 350, func: null, loops: false }, // !close
  6412: { instr: 482, func: null, loops: false },
  6420: { instr: 282, func: null, loops: true }, // parent
  6432: { instr: 772, func: null, loops: true }, // rename
  6448: { instr: 374, func: null, loops: true }, // kill
  6460: { instr: null, func: 64, loops: false }, // drive
  6472: { instr: 2142, func: null, loops: true }, // field
  6484: { instr: null, func: 7436, loops: true }, // !fsel$
  6498: { instr: null, func: 7424, loops: true },
  6508: { instr: null, func: 7412, loops: true },
  6520: { instr: null, func: 7374, loops: true },
  6534: { instr: 3012, func: null, loops: false }, // set sprite buffer
  6558: { instr: 792, func: null, loops: false }, // !sprite off
  6576: { instr: 784, func: null, loops: false },
  6584: { instr: 324, func: null, loops: false }, // sprite priority
  6606: { instr: 32, func: null, loops: false }, // sprite update off
  6630: { instr: 32, func: null, loops: false }, // sprite update on
  6652: { instr: 816, func: null, loops: false }, // sprite update
  6672: { instr: null, func: 814, loops: false }, // !spritebob col
  6694: { instr: null, func: 846, loops: false },
  6706: { instr: null, func: 798, loops: false }, // !sprite col
  6724: { instr: null, func: 850, loops: false },
  6736: { instr: 202, func: null, loops: false }, // set hardcol
  6756: { instr: null, func: 488, loops: true }, // hardcol
  6770: { instr: null, func: 108, loops: true }, // sprite base
  6788: { instr: null, func: 108, loops: true }, // icon base
  6804: { instr: 132, func: null, loops: false }, // sprite
  6824: { instr: 236, func: null, loops: false }, // !bob off
  6838: { instr: 168, func: null, loops: false },
  6846: { instr: 32, func: null, loops: false }, // bob update off
  6866: { instr: 32, func: null, loops: false }, // bob update on
  6886: { instr: 2044, func: null, loops: false }, // bob update
  6902: { instr: 398, func: null, loops: false }, // bob clear
  6918: { instr: 1366, func: null, loops: false }, // bob draw
  6932: { instr: null, func: 806, loops: false }, // !bobsprite col
  6954: { instr: null, func: 858, loops: false },
  6966: { instr: null, func: 806, loops: false }, // !bob col
  6982: { instr: null, func: 838, loops: false },
  6994: { instr: null, func: 170, loops: false }, // col
  7004: { instr: 266, func: null, loops: false }, // !limit bob
  7020: { instr: 282, func: null, loops: false },
  7034: { instr: 290, func: null, loops: false },
  7050: { instr: 434, func: null, loops: true }, // set bob
  7070: { instr: 262, func: null, loops: false }, // bob
  7086: { instr: 790, func: null, loops: false }, // !get sprite palette
  7112: { instr: 776, func: null, loops: false },
  7120: { instr: 1216, func: null, loops: true }, // !get sprite
  7146: { instr: 1336, func: null, loops: true },
  7164: { instr: 1216, func: null, loops: true }, // !get bob
  7188: { instr: 1336, func: null, loops: true },
  7206: { instr: 1744, func: null, loops: true }, // !del sprite
  7224: { instr: 1722, func: null, loops: true },
  7234: { instr: 1744, func: null, loops: true }, // !del bob
  7250: { instr: 1722, func: null, loops: true },
  7260: { instr: 1744, func: null, loops: true }, // !del icon
  7276: { instr: 1722, func: null, loops: true },
  7286: { instr: 1532, func: null, loops: false }, // ins sprite
  7304: { instr: 1532, func: null, loops: false }, // ins bob
  7318: { instr: 1532, func: null, loops: false }, // ins icon
  7334: { instr: 790, func: null, loops: false }, // !get icon palette
  7358: { instr: 776, func: null, loops: false },
  7366: { instr: 1216, func: null, loops: true }, // !get icon
  7390: { instr: 1336, func: null, loops: true },
  7408: { instr: 258, func: null, loops: false }, // put bob
  7422: { instr: 6490, func: null, loops: false }, // paste bob
  7442: { instr: 6514, func: null, loops: true }, // paste icon
  7464: { instr: 1876, func: null, loops: true }, // !make mask
  7480: { instr: 1876, func: null, loops: true },
  7488: { instr: 612, func: null, loops: true }, // !no mask
  7502: { instr: 612, func: null, loops: true },
  7510: { instr: 1876, func: null, loops: true }, // !make icon mask
  7532: { instr: 1876, func: null, loops: true },
  7540: { instr: 612, func: null, loops: true }, // !no icon mask
  7560: { instr: 612, func: null, loops: true },
  7568: { instr: 812, func: null, loops: false }, // !hot spot
  7586: { instr: 812, func: null, loops: false },
  7598: { instr: 202, func: null, loops: false }, // priority on
  7616: { instr: 202, func: null, loops: false }, // priority off
  7634: { instr: 130, func: null, loops: false }, // hide on
  7648: { instr: 130, func: null, loops: false }, // hide
  7658: { instr: 130, func: null, loops: false }, // show on
  7672: { instr: 130, func: null, loops: false }, // show
  7682: { instr: 174, func: null, loops: false }, // change mouse
  7702: { instr: 352, func: 128, loops: false }, // x mouse
  7716: { instr: 352, func: 128, loops: false }, // y mouse
  7730: { instr: null, func: 198, loops: false }, // mouse key
  7746: { instr: null, func: 296, loops: false }, // mouse click
  7764: { instr: 834, func: null, loops: false }, // !limit mouse
  7782: { instr: 854, func: null, loops: false },
  7790: { instr: 344, func: null, loops: false },
  7804: { instr: 162, func: null, loops: false }, // unfreeze
  7818: { instr: 708, func: null, loops: true }, // !move x
  7834: { instr: 736, func: null, loops: true },
  7846: { instr: 708, func: null, loops: true }, // !move y
  7862: { instr: 736, func: null, loops: true },
  7874: { instr: 636, func: null, loops: false }, // !move off
  7890: { instr: 640, func: null, loops: false },
  7898: { instr: 636, func: null, loops: false }, // !move on
  7912: { instr: 640, func: null, loops: false },
  7920: { instr: 636, func: null, loops: false }, // !move freeze
  7938: { instr: 640, func: null, loops: false },
  7946: { instr: 636, func: null, loops: false }, // !anim off
  7962: { instr: 640, func: null, loops: false },
  7970: { instr: 636, func: null, loops: false }, // !anim on
  7984: { instr: 640, func: null, loops: false },
  7992: { instr: 636, func: null, loops: false }, // !anim freeze
  8010: { instr: 640, func: null, loops: false },
  8018: { instr: 708, func: null, loops: true }, // anim
  8032: { instr: 736, func: null, loops: true },
  8044: { instr: null, func: 350, loops: false }, // movon
  8056: { instr: null, func: 1032, loops: false }, // chanan
  8070: { instr: null, func: 892, loops: false }, // chanmv
  8084: { instr: 600, func: null, loops: true }, // channel
  8098: { instr: 150, func: 142, loops: false }, // !amreg
  8112: { instr: 150, func: 142, loops: false },
  8124: { instr: 636, func: null, loops: false }, // !amal on
  8138: { instr: 640, func: null, loops: false },
  8146: { instr: 636, func: null, loops: false }, // !amal off
  8162: { instr: 640, func: null, loops: false },
  8170: { instr: 636, func: null, loops: false }, // !amal freeze
  8188: { instr: 640, func: null, loops: false },
  8196: { instr: null, func: 36, loops: false }, // amalerr
  8210: { instr: 708, func: null, loops: true }, // !amal
  8224: { instr: 736, func: null, loops: true },
  8236: { instr: 408, func: null, loops: false }, // !amplay
  8252: { instr: 360, func: null, loops: false },
  8266: { instr: 116, func: null, loops: false }, // synchro on
  8282: { instr: 112, func: null, loops: false }, // synchro off
  8300: { instr: 646, func: null, loops: false }, // synchro
  8314: { instr: 48, func: null, loops: false }, // update off
  8330: { instr: 48, func: null, loops: false }, // update on
  8346: { instr: 56, func: null, loops: false }, // update every
  8366: { instr: 2800, func: null, loops: false }, // update
  8378: { instr: null, func: 286, loops: false }, // x bob
  8390: { instr: null, func: 286, loops: false }, // y bob
  8402: { instr: null, func: 246, loops: false }, // x sprite
  8418: { instr: null, func: 246, loops: false }, // y sprite
  8434: { instr: 2042, func: null, loops: true }, // reserve as work
  8458: { instr: 2042, func: null, loops: true }, // reserve as chip work
  8488: { instr: 2042, func: null, loops: true }, // reserve as data
  8512: { instr: 2042, func: null, loops: true }, // reserve as chip data
  8542: { instr: 1814, func: null, loops: true }, // erase
  8554: { instr: 764, func: null, loops: true }, // list bank
  8570: { instr: null, func: 126, loops: false }, // chip free
  8586: { instr: null, func: 126, loops: false }, // fast free
  8602: { instr: 468, func: null, loops: false }, // fill
  8618: { instr: 384, func: null, loops: false }, // copy
  8634: { instr: null, func: 500, loops: true }, // hunt
  8650: { instr: 36, func: null, loops: false }, // poke
  8664: { instr: 58, func: null, loops: true }, // loke
  8678: { instr: null, func: 36, loops: false }, // peek
  8690: { instr: null, func: 46, loops: true }, // deek
  8702: { instr: null, func: 46, loops: true }, // leek
  8714: { instr: 458, func: null, loops: true }, // bset
  8728: { instr: 458, func: null, loops: true }, // bclr
  8742: { instr: 458, func: null, loops: true }, // bchg
  8756: { instr: null, func: 454, loops: true }, // btst
  8770: { instr: 464, func: null, loops: true }, // ror.b
  8784: { instr: 464, func: null, loops: true }, // ror.w
  8798: { instr: 466, func: null, loops: true }, // ror.l
  8812: { instr: 464, func: null, loops: true }, // rol.b
  8826: { instr: 464, func: null, loops: true }, // rol.w
  8840: { instr: 466, func: null, loops: true }, // rol.l
  8854: { instr: 146, func: 142, loops: false }, // areg
  8866: { instr: 146, func: 142, loops: false }, // dreg
  8878: { instr: 730, func: null, loops: false }, // copper on
  8894: { instr: 730, func: null, loops: false }, // copper off
  8910: { instr: 118, func: null, loops: false }, // cop swap
  8924: { instr: 118, func: null, loops: false }, // cop reset
  8940: { instr: 196, func: null, loops: false }, // !cop wait
  8958: { instr: 158, func: null, loops: false },
  8972: { instr: 464, func: null, loops: false }, // cop movel
  8990: { instr: 258, func: null, loops: false }, // cop move
  9008: { instr: null, func: 120, loops: false }, // cop logic
  9024: { instr: null, func: 1412, loops: true }, // prg first$
  9042: { instr: null, func: 976, loops: true }, // prg next$
  9058: { instr: null, func: 16, loops: false }, // !psel$
  9072: { instr: null, func: 16, loops: false },
  9082: { instr: null, func: 16, loops: false },
  9094: { instr: null, func: 16, loops: false },
  9108: { instr: 36, func: null, loops: true }, // prun
  9120: { instr: 2098, func: null, loops: true }, // bgrab
  9132: { instr: 960, func: null, loops: true }, // put
  9144: { instr: 1072, func: null, loops: true }, // get
  9156: { instr: 18, func: null, loops: false }, // system
  9168: { instr: 92, func: null, loops: false }, // multi wait
  9184: { instr: null, func: 282, loops: false }, // i bob
  9196: { instr: null, func: 242, loops: false }, // i sprite
  9212: { instr: 202, func: null, loops: false }, // priority reverse on
  9238: { instr: 202, func: null, loops: false }, // priority reverse off
  9264: { instr: null, func: 1412, loops: true }, // dev first$
  9282: { instr: null, func: 976, loops: true }, // dev next$
  9298: { instr: 448, func: null, loops: false }, // hrev block
  9316: { instr: 448, func: null, loops: false }, // vrev block
  9334: { instr: null, func: 28, loops: false }, // hrev
  9346: { instr: null, func: 28, loops: false }, // vrev
  9358: { instr: null, func: 36, loops: false }, // rev
  9368: { instr: 466, func: null, loops: true }, // bank swap
  9386: { instr: 72, func: null, loops: false }, // amos to front
  9406: { instr: 72, func: null, loops: false }, // amos to back
  9424: { instr: null, func: 80, loops: false }, // amos here
  9440: { instr: 88, func: null, loops: false }, // amos lock
  9456: { instr: 32, func: null, loops: false }, // amos unlock
  9474: { instr: null, func: 116, loops: false }, // display height
  9494: { instr: null, func: 584, loops: false }, // ntsc
  9504: { instr: null, func: 24, loops: false }, // laced
  9516: { instr: null, func: 36, loops: false }, // prg state
  9532: { instr: 150, func: 90, loops: true }, // command line$
  9552: { instr: null, func: 976, loops: true }, // disc info$
  9570: { instr: 26, func: 26, loops: false }, // \\\\\\\\\\\\\\\/
  9592: { instr: 16, func: null, loops: false }, // set accessory
  9612: { instr: 898, func: null, loops: true }, // @_apml_@
  9626: { instr: 56, func: null, loops: false }, // trap
  9636: { instr: 164, func: null, loops: true }, // else if
  9650: { instr: null, func: null, loops: false }, // include
  9664: { instr: null, func: 112, loops: true }, // array
  9676: { instr: null, func: 4756, loops: true }, // !frame load
  9696: { instr: null, func: 4730, loops: true },
  9708: { instr: null, func: 1066, loops: false }, // !frame play
  9728: { instr: null, func: 1032, loops: false },
  9740: { instr: 936, func: null, loops: true }, // !iff anim
  9758: { instr: 910, func: null, loops: true },
  9770: { instr: null, func: 1162, loops: false }, // !frame length
  9790: { instr: null, func: 1136, loops: false },
  9800: { instr: null, func: 1042, loops: false }, // !frame skip
  9818: { instr: null, func: 1016, loops: false },
  9828: { instr: null, func: 36, loops: false }, // !frame param
  9846: { instr: 1094, func: null, loops: true }, // !call editor
  9866: { instr: 1082, func: null, loops: true },
  9876: { instr: 1048, func: null, loops: true },
  9888: { instr: 864, func: null, loops: true }, // !ask editor
  9906: { instr: 852, func: null, loops: true },
  9916: { instr: 818, func: null, loops: true },
  9928: { instr: 1704, func: null, loops: true }, // erase temp
  9944: { instr: 1678, func: null, loops: true }, // erase all
  9960: { instr: null, func: 502, loops: true }, // !dialog box
  9978: { instr: null, func: 490, loops: true },
  9988: { instr: null, func: 466, loops: true },
  10000: { instr: null, func: 420, loops: true },
  10016: { instr: 388, func: null, loops: true }, // !dialog open
  10038: { instr: 368, func: null, loops: true },
  10050: { instr: 334, func: null, loops: true },
  10064: { instr: 950, func: null, loops: false }, // !dialog close
  10084: { instr: 894, func: null, loops: false },
  10092: { instr: null, func: 936, loops: true }, // !dialog run
  10110: { instr: null, func: 916, loops: true },
  10120: { instr: null, func: 870, loops: true },
  10134: { instr: null, func: 288, loops: false }, // dialog
  10148: { instr: 310, func: 306, loops: false }, // vdialog
  10166: { instr: 320, func: 306, loops: false }, // vdialog$
  10184: { instr: null, func: 370, loops: true }, // !rdialog
  10202: { instr: null, func: 344, loops: true },
  10214: { instr: null, func: 376, loops: true }, // !rdialog$
  10232: { instr: null, func: 350, loops: true },
  10244: { instr: null, func: 36, loops: false }, // edialog
  10258: { instr: 468, func: null, loops: false }, // dialog clr
  10276: { instr: 3184, func: null, loops: false }, // !dialog update
  10300: { instr: 3172, func: null, loops: false },
  10312: { instr: 3160, func: null, loops: false },
  10326: { instr: 3126, func: null, loops: false },
  10342: { instr: 90, func: null, loops: false }, // !dialog freeze
  10362: { instr: 350, func: null, loops: false },
  10370: { instr: 90, func: null, loops: false }, // !dialog unfreeze
  10392: { instr: 350, func: null, loops: false },
  10400: { instr: 72, func: null, loops: true }, // poke$
  10414: { instr: null, func: 172, loops: true }, // !peek$
  10430: { instr: null, func: 196, loops: true },
  10442: { instr: 48, func: null, loops: false }, // resource bank
  10462: { instr: null, func: 324, loops: true }, // resource$
  10478: { instr: 594, func: null, loops: false }, // resource screen open
  10512: { instr: 668, func: null, loops: false }, // resource unpack
  10538: { instr: 1004, func: null, loops: true }, // read text
  10554: { instr: 1174, func: null, loops: true },
  10566: { instr: null, func: 124, loops: true }, // err$
  10578: { instr: 1252, func: null, loops: true }, // assign
  10594: { instr: null, func: 36, loops: false }, // errtrap
  10608: { instr: 1206, func: null, loops: true }, // dev open
  10632: { instr: 938, func: null, loops: true }, // !dev close
  10648: { instr: 848, func: null, loops: true },
  10656: { instr: null, func: 188, loops: false }, // dev base
  10672: { instr: 508, func: null, loops: true }, // dev do
  10688: { instr: 492, func: null, loops: true }, // dev send
  10706: { instr: 358, func: null, loops: true }, // dev abort
  10722: { instr: null, func: 304, loops: false }, // dev check
  10738: { instr: 484, func: null, loops: true }, // lib open
  10758: { instr: 290, func: null, loops: true }, // !lib close
  10774: { instr: 238, func: null, loops: true },
  10782: { instr: null, func: 0, loops: true }, // lib call
  10800: { instr: null, func: 120, loops: false }, // lib base
  10816: { instr: null, func: 76, loops: false }, // equ
  10826: { instr: null, func: 76, loops: false }, // lvo
  10836: { instr: 586, func: null, loops: false }, // struc
  10852: { instr: 734, func: null, loops: true }, // struc$
  10868: { instr: null, func: 224, loops: false }, // bstart
  10882: { instr: null, func: 288, loops: true }, // blength
  10896: { instr: 2142, func: null, loops: true }, // bsend
  10908: { instr: 658, func: null, loops: false }, // bank shrink
  10928: { instr: null, func: 166, loops: true }, // prg under
  10944: { instr: 334, func: null, loops: true }, // arexx open
  10962: { instr: 340, func: null, loops: true }, // arexx close
  10980: { instr: null, func: 492, loops: false }, // arexx exist
  10998: { instr: null, func: 404, loops: true }, // arexx
  11010: { instr: null, func: 90, loops: true }, // arexx$
  11024: { instr: 408, func: null, loops: true }, // arexx wait
  11040: { instr: 406, func: null, loops: true }, // !arexx answer
  11060: { instr: 368, func: null, loops: true },
  11070: { instr: 390, func: null, loops: true }, // exec
  11082: { instr: 0, func: null, loops: false }, // monitor
  11096: { instr: null, func: 114, loops: false }, // screen mode
  11114: { instr: null, func: 64, loops: true },
  11122: { instr: 0, func: null, loops: false }, // kill editor
  11140: { instr: 16, func: null, loops: false }, // set double precision
  11166: { instr: 16, func: null, loops: false }, // set stack
  11182: { instr: 790, func: null, loops: false }, // !get bob palette
  11204: { instr: 776, func: null, loops: false },
  11212: { instr: 16, func: null, loops: false }, // set equate bank
  11234: { instr: null, func: 312, loops: false }, // zdialog
  11252: { instr: 138, func: null, loops: true }, // ||apcmp||
}
