// GENERATED by src/cli/genpiconfig.ts — do not edit.
// Source: +Interpreter_Config.s (defaults) / +Equ.s:1590-1650 (layout).

/**
 * The interpreter configuration block AMOS keeps at a5. These are the
 * editor-editable defaults, and some are written back at run time —
 * Fs_Close (+Lib.s:18469) stores the file selector's toggles and window
 * position here, so they survive from one Fsel$ to the next.
 *
 * Field names are the AMOS ones with the PI_ prefix dropped, and the
 * comment on each is its byte offset in the original block.
 */
export interface PiConfig {
  /** +0 */
  ParaTrap: number
  /** +4 */
  AdMouse: number
  /** +20 */
  VNmMax: number
  /** +24 */
  TVDirect: number
  /** +26 */
  DefSize: number
  /** +30 */
  DirSize: number
  /** +32 */
  DirMax: number
  /** +34 */
  PrtRet: number
  /** +35 */
  Icons: number
  /** +36 */
  AutoWB: number
  /** +37 */
  AllowWB: number
  /** +38 */
  CloseEd: number
  /** +39 */
  KillEd: number
  /** +40 */
  FsSort: number
  /** +41 */
  FsSize: number
  /** +42 */
  FsStore: number
  /** +48 */
  RtSx: number
  /** +50 */
  RtSy: number
  /** +52 */
  RtWx: number
  /** +54 */
  RtWy: number
  /** +56 */
  RtSpeed: number
  /** +58 */
  FsDSx: number
  /** +60 */
  FsDSy: number
  /** +62 */
  FsDWx: number
  /** +64 */
  FsDWy: number
  /** +66 */
  FsDVApp: number
  /** +68 */
  DefETx: number
  /** +70 */
  DefETy: number
  /** +72 */
  DefECo: number
  /** +74 */
  DefECoN: number
  /** +76 */
  DefEMo: number
  /** +78 */
  DefEBa: number
  /** +144 */
  DefEWx: number
  /** +146 */
  DefEWy: number
  /** +148 */
  DefAmigA: number
  /** +80, 32 entries */
  DefEPa: number[]
}

export const PI_DEFAULTS: PiConfig = {
  ParaTrap: 0,
  AdMouse: 0,
  VNmMax: 1024,
  TVDirect: 42,
  DefSize: 1024,
  DirSize: 30,
  DirMax: 128,
  PrtRet: 1,
  Icons: 0,
  AutoWB: 0,
  AllowWB: 1,
  CloseEd: 1,
  KillEd: 1,
  FsSort: 1,
  FsSize: 1,
  FsStore: 1,
  RtSx: 640,
  RtSy: 200,
  RtWx: 129,
  RtWy: 50,
  RtSpeed: 8,
  FsDSx: 448,
  FsDSy: 158,
  FsDWx: 177,
  FsDWy: 70,
  FsDVApp: 8,
  DefETx: 320,
  DefETy: 200,
  DefECo: 4,
  DefECoN: 16,
  DefEMo: 0,
  DefEBa: 0,
  DefEWx: 0,
  DefEWy: 0,
  DefAmigA: 4211041,
  DefEPa: [0, 2624, 4095, 0, 3840, 240, 15, 1638, 1365, 819, 1843, 883, 1907, 823, 1847, 887, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
}

/** a fresh mutable copy — the running interpreter edits its own */
export const newPiConfig = (): PiConfig => ({
  ...PI_DEFAULTS,
  DefEPa: [...PI_DEFAULTS.DefEPa],
})
