/**
 * Generate src/ext/amoscalls.gen.ts — the tables that make extension
 * disassembly readable.
 *
 * An extension calls back into AMOS through a four-byte pseudo-instruction,
 * not a real 68k opcode, which is why a disassembler renders it as garbage
 * and stops. +CEqu.s:39-150 defines the encoding:
 *
 *     Rbsr MACRO
 *          dc.b  C_Code1, 3*16+C_Code2      ; $FE, $31
 *          dc.w  <routine number>
 *          ENDM
 *
 * so `$fe31 $000e` is `Rbsr L_<14>`. The routine numbers are the L_ labels
 * in "AMOSPro Sources/+lib_Labels.s", which is how a call becomes a name we
 * can look up in the AMOS source we already have.
 *
 *   npx tsx src/cli/genamoscalls.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const cequ = readFileSync(join(root, '+CEqu.s'), 'latin1')

/**
 * kind nibble -> macro name, keyed by which SELECTOR byte follows.
 *
 * There are exactly three shapes, and the selector is what tells them apart:
 *
 *   none     $FE kk01 wwww                 4 bytes — Rbra, Rbsr, Rbcc, ...
 *   C_CodeT  $FE kk01 $F5 rr wwww          6 bytes — Rjmpt, Rjsrt, Rlea
 *   C_CodeJ  $FE kk01 $F7 ll wwww          6 bytes — Rjmp, Rjsr, Ljmp, Ljsr
 *
 * Reading this off `dc.b C_CodeJ` alone was the bug: C_CodeT is a selector
 * too, so every kind-0 and kind-1 macro carrying one was filed as the plain
 * four-byte form. `Rjsr` is the commonest call in extension code, and a
 * disassembler that reads it as four bytes runs two bytes out of step for
 * the whole rest of the routine.
 */
const kinds = new Map<string, { kind: number; name: string; sel: 'plain' | 't' | 'j' }>()
for (const m of cequ.matchAll(/^(\w+)\s+MACRO\s*\n((?:.*\n){1,4}?)\s+ENDM/gm)) {
  const [, name, body] = m
  const enc = /dc\.b\s+C_Code1,\s*(\d+)\*16\+C_Code2/.exec(body!)
  if (!enc) continue
  const sel = /dc\.b\s+C_CodeJ/.test(body!) ? 'j' : /dc\.b\s+C_CodeT/.test(body!) ? 't' : 'plain'
  const key = `${enc[1]}:${sel}`
  // keep the first of each shape: Rjmpt before RjmptR, Rjmp before Ljmp
  if (!kinds.has(key)) kinds.set(key, { kind: Number(enc[1]), name: name!, sel })
}

/** the selector byte values, read from +CEqu.s rather than assumed */
const selValue = (which: 'T' | 'J'): number => {
  const m = new RegExp(`^C_Code${which}\\s+equ\\s+\\$([0-9A-Fa-f]+)`, 'm').exec(cequ)
  if (!m) throw new Error(`C_Code${which} not found in +CEqu.s`)
  return parseInt(m[1]!, 16)
}

const labels = readFileSync(join(root, 'AMOSPro Sources', '+lib_Labels.s'), 'latin1')
const routines: Array<[number, string]> = []
for (const m of labels.matchAll(/^(L_[\w.]+):?\s+set\s+(\d+)/gm)) routines.push([Number(m[2]), m[1]!])

/**
 * The numbering an EXTENSION actually uses, which is not this one.
 *
 * `+lib_Labels.s` is AMOS Pro 2.0's own external list. An extension binary
 * holds something else: the numbering of the developer kit it was written
 * against, whose header says exactly what it is —
 *
 *     ; AMOS 1.34 Compiler librarie numbers
 *     ; + AMOSPro V1.0 extension functions
 *
 * AMOS Pro 2.0 knows this and translates at LOAD time. `+B.s:2627` tests
 * `LBF_20` — set only when the library file carries the magic `AP20`, which
 * two of seventy-one third-party binaries here do — and for everything else
 * runs `Ext_OldLabel`, a lookup in the 31-entry `Ext_Convert` table headed
 * "Table de conversion des labels AMOSPro 1.0 >>> AMOSPro 2.0".
 */
const lequ = readFileSync(join(root, 'extensions', 'Intuition-41.95', 'AMOS', 'LEqu.s'), 'latin1')
// several numbers carry two names (`L_Bnk_GetAdr` and `L_AdOuBank` are the
// same routine under the 1.34 and the Pro 1.0 spelling); keep the first
const byNumber = new Map<number, string>()
for (const m of lequ.matchAll(/^(L_\w+)\s+equ\s+(\d+)\s*$/gm)) {
  const n = Number(m[2])
  if (!byNumber.has(n)) byNumber.set(n, m[1]!)
}
const extLabels: Array<[number, string]> = [...byNumber]

/** `Ext_Convert` (+B.s): the old numbers AMOS Pro 2.0 rewrites, and to what */
const convert: Array<[number, string]> = []
const bs = readFileSync(join(root, '+B.s'), 'latin1')
for (const m of bs.slice(bs.indexOf('Ext_Convert')).matchAll(/^\s+dc\.w\s+(\d+),(L_[\w.]+)\s*$/gm)) {
  if (m[1] === '0') break
  convert.push([Number(m[1]), m[2]!])
}

const out = [
  '// GENERATED by src/cli/genamoscalls.ts — do not edit.',
  '// Source: +CEqu.s (the call encoding), AMOSPro Sources/+lib_Labels.s (names).',
  '',
  '/**',
  ' * How an extension calls back into AMOS: a pseudo-instruction of $FE,',
  ' * kind*16+$01, optionally a SELECTOR byte pair, then a word holding the',
  ' * routine number. Not a real 68k opcode, which is why a disassembler',
  ' * chokes on it — and in 020 mode capstone is worse than useless here,',
  ' * because it decodes the $F-line word as a coprocessor instruction and',
  ' * silently swallows whatever follows.',
  ' */',
  'export const AMOS_CALL_MARKER = 0xfe',
  'export const AMOS_CALL_LOW = 0x01',
  '',
  '/** C_CodeT — the selector on Rjmpt/Rjsrt/Rlea; second byte is a register */',
  `export const AMOS_CALL_SEL_T = 0x${selValue('T').toString(16)}`,
  '/** C_CodeJ — the selector on Rjmp/Rjsr/Ljmp/Ljsr; second byte is a library */',
  `export const AMOS_CALL_SEL_J = 0x${selValue('J').toString(16)}`,
  '',
  '/**',
  ' * kind nibble -> the forms it can take, keyed by selector.',
  ' *',
  ' * `plain` is four bytes and targets a routine in the CALLING library.',
  ' * `t` and `j` are SIX, the extra pair being the selector and its operand.',
  ' * Kinds 0 and 1 have no plain form at all — every macro that uses them',
  ' * carries a selector — so a decoder that treats them as four bytes runs',
  ' * two bytes out of step for the rest of the routine.',
  ' */',
  'export const AMOS_CALL_KINDS: Record<number, { plain?: string; t?: string; j?: string }> = {',
  ...[...new Set([...kinds.values()].map((k) => k.kind))]
    .sort((a, b) => a - b)
    .map((kind) => {
      const parts: string[] = []
      for (const sel of ['plain', 't', 'j'] as const) {
        const hit = [...kinds.values()].find((k) => k.kind === kind && k.sel === sel)
        if (hit) parts.push(`${sel}: ${JSON.stringify(hit.name)}`)
      }
      return `  ${kind}: { ${parts.join(', ')} },`
    }),
  '}',
  '',
  '/**',
  ' * AMOS routine number -> its L_ label. This applies ONLY to cross-library',
  ' * calls (Ljmp/Ljsr, the ones carrying a library selector). An extension',
  " * using the plain form is calling ITS OWN routine table — verified on LDos,",
  ' * where `Rbsr 14` from Lfile Type lands on that library\'s own',
  ' * string-to-C-string helper, not on AMOS routine 14 (which is L_FnLn).',
  ' */',
  'export const AMOS_ROUTINES: Record<number, string> = {',
  ...routines.sort((a, b) => a[0] - b[0]).map(([n, l]) => `  ${n}: ${JSON.stringify(l)},`),
  '}',
  '',
  '/**',
  ' * The numbering an EXTENSION uses when it calls library 0.',
  ' *',
  ' * NOT `AMOS_ROUTINES`. An extension binary carries the numbers of the',
  ' * developer kit it was written against, and that kit is the AMOS 1.34 /',
  ' * AMOS Pro 1.0 one, whose list says so in its own header:',
  ' *',
  ' *     ; AMOS 1.34 Compiler librarie numbers',
  ' *     ; + AMOSPro V1.0 extension functions',
  ' *',
  ' * AMOS Pro 2.0 translates them as it relocates the library (`+B.s:2627`),',
  ' * so a program never sees the difference and neither did this port, which',
  ' * read them against the 2.0 list and got plausible wrong answers: 1025 is',
  " * `L_Dia_ScCopy` there and `L_ErrorExt` here, and it is the number fifty-two",
  ' * extensions use to raise their own error requester.',
  ' *',
  ' * Confirmed, not assumed. `Ext_Convert` below rewrites 31 of these numbers,',
  ' * and for 21 of the 31 both lists have the target name: every one agrees',
  ' * (`1100 -> L_Bnk_GetAdr` here, `797` there, and `797 - 500 = 297` is',
  ' * `L_Bnk.GetAdr` in `+lib_Labels.s`). The other ten are labels `+lib_Labels.s`',
  ' * does not carry at all. There are no disagreements.',
  ' */',
  'export const AMOS_EXT_LABELS: Record<number, string> = {',
  ...extLabels.sort((a, b) => a[0] - b[0]).map(([n, l]) => `  ${n}: ${JSON.stringify(l)},`),
  '}',
  '',
  '/**',
  ' * `Ext_Convert` (+B.s), the 31 numbers AMOS Pro 2.0 rewrites at load time',
  ' * for any library without the `AP20` magic — which is nearly all of them.',
  ' *',
  ' * Read out of the shipped `AMOSPro` executable at $4f26 as well as out of',
  ' * the source, and the two agree entry for entry. Kept because it is the',
  ' * evidence for the numbering above, and because a call NOT in this table',
  ' * is one an old library cannot make: `Ext_OldLabel` falls through to',
  ' * `Ll_BadExt` — error 2, the library does not load.',
  ' */',
  'export const AMOS_EXT_CONVERT: Record<number, string> = {',
  ...convert.sort((a, b) => a[0] - b[0]).map(([n, l]) => `  ${n}: ${JSON.stringify(l)},`),
  '}',
  '',
]
writeFileSync('src/ext/amoscalls.gen.ts', out.join('\n'))
console.log(
  `src/ext/amoscalls.gen.ts: ${kinds.size} call forms, ${routines.length} 2.0 labels, ` +
    `${extLabels.length} extension labels, ${convert.length} conversions`,
)
