/**
 * Generate src/ext/amoscalls.gen.ts — the tables that make extension
 * disassembly readable.
 *
 * An extension calls back into AMOS through a four-byte pseudo-instruction,
 * not a real 68k opcode, which is why a disassembler renders it as garbage
 * and stops. +CEqu.s:39-150 defines the encoding:
 *
 *     Rbsr MACRO
 *          dc.b  C_Code1, 3*16+C_Code2      ; $FE, $31
 *          dc.w  <routine number>
 *          ENDM
 *
 * so `$fe31 $000e` is `Rbsr L_<14>`. The routine numbers are the L_ labels
 * in "AMOSPro Sources/+lib_Labels.s", which is how a call becomes a name we
 * can look up in the AMOS source we already have.
 *
 *   npx tsx src/cli/genamoscalls.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const cequ = readFileSync(join(root, '+CEqu.s'), 'latin1')

/**
 * kind nibble -> macro name. Several macros share a nibble and are told
 * apart by whether a C_CodeJ library-selector byte pair follows, so the key
 * is (kind, hasSelector) and the plain intra-library form is preferred as
 * the display name.
 */
const kinds = new Map<string, { kind: number; name: string; extra: number }>()
for (const m of cequ.matchAll(/^(\w+)\s+MACRO\s*\n((?:.*\n){1,4}?)\s+ENDM/gm)) {
  const [, name, body] = m
  const enc = /dc\.b\s+C_Code1,\s*(\d+)\*16\+C_Code2/.exec(body!)
  if (!enc) continue
  const extra = /dc\.b\s+C_CodeJ/.test(body!) ? 2 : 0
  const key = `${enc[1]}:${extra}`
  // keep the first, which is the plain form; later ones are variants
  if (!kinds.has(key)) kinds.set(key, { kind: Number(enc[1]), name: name!, extra })
}

const labels = readFileSync(join(root, 'AMOSPro Sources', '+lib_Labels.s'), 'latin1')
const routines: Array<[number, string]> = []
for (const m of labels.matchAll(/^(L_\w+):?\s+set\s+(\d+)/gm)) routines.push([Number(m[2]), m[1]!])

const out = [
  '// GENERATED by src/cli/genamoscalls.ts — do not edit.',
  '// Source: +CEqu.s (the call encoding), AMOSPro Sources/+lib_Labels.s (names).',
  '',
  '/**',
  ' * How an extension calls back into AMOS: a four-byte pseudo-instruction of',
  ' * $FE, kind*16+$01, then a word holding the AMOS routine number. Not a real',
  ' * 68k opcode, which is why a disassembler chokes on it.',
  ' */',
  'export const AMOS_CALL_MARKER = 0xfe',
  'export const AMOS_CALL_LOW = 0x01',
  '',
  '/**',
  ' * kind nibble -> the two forms it can take. `plain` is an intra-library',
  ' * call whose word is a routine number in the CALLING library; `viaLib`',
  ' * carries a C_CodeJ library selector first and targets another library.',
  ' */',
  'export const AMOS_CALL_KINDS: Record<number, { plain?: string; viaLib?: string }> = {',
  ...[...new Set([...kinds.values()].map((k) => k.kind))]
    .sort((a, b) => a - b)
    .map((kind) => {
      const plain = [...kinds.values()].find((k) => k.kind === kind && k.extra === 0)
      const viaLib = [...kinds.values()].find((k) => k.kind === kind && k.extra === 2)
      const parts: string[] = []
      if (plain) parts.push(`plain: ${JSON.stringify(plain.name)}`)
      if (viaLib) parts.push(`viaLib: ${JSON.stringify(viaLib.name)}`)
      return `  ${kind}: { ${parts.join(', ')} },`
    }),
  '}',
  '',
  '/**',
  ' * AMOS routine number -> its L_ label. This applies ONLY to cross-library',
  ' * calls (Ljmp/Ljsr, the ones carrying a library selector). An extension',
  " * using the plain form is calling ITS OWN routine table — verified on LDos,",
  ' * where `Rbsr 14` from Lfile Type lands on that library\'s own',
  ' * string-to-C-string helper, not on AMOS routine 14 (which is L_FnLn).',
  ' */',
  'export const AMOS_ROUTINES: Record<number, string> = {',
  ...routines.sort((a, b) => a[0] - b[0]).map(([n, l]) => `  ${n}: ${JSON.stringify(l)},`),
  '}',
  '',
]
writeFileSync('src/ext/amoscalls.gen.ts', out.join('\n'))
console.log(`src/ext/amoscalls.gen.ts: ${kinds.size} call forms, ${routines.length} routine names`)
