/**
 * Generate src/amiga/datatypes.gen.ts from real `DEVS:DataTypes` descriptors.
 *
 * A descriptor is a file, not a table compiled into the library: Commodore
 * shipped `datatypes.library` empty and the formats it knows arrive by
 * dropping IFF `FORM DTYP` files into a drawer. That is the whole design, and
 * it is why this generator exists rather than a hand-written table. What it
 * emits is what those files say.
 *
 * The AMOS PD Library CD (Weird Science, 1994) carries a Workbench 3.0
 * `Devs/DataTypes` drawer with eleven of them, which is the set below. They
 * are Commodore's and the Picture DataTypes package's; none is ours.
 *
 *   npx tsx src/cli/gendatatypes.ts [dir]
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { DTHD, parseDescriptor, type DataTypeHeader } from '../amiga/datatypes'

const DEFAULT = '../amos-files/sources/amos-pd-library-cd-1994/files/Devs/DataTypes'
const dir = process.argv[2] ?? DEFAULT

const found: DataTypeHeader[] = []
for (const name of readdirSync(dir).sort()) {
  const path = join(dir, name)
  if (!statSync(path).isFile()) continue
  const dt = parseDescriptor(new Uint8Array(readFileSync(path)))
  if (dt !== null) found.push(dt)
}
if (found.length === 0) throw new Error(`no FORM DTYP descriptors in ${dir}`)

/** the mask, as the source that produced it: literals as chars where printable */
function maskLiteral(mask: readonly number[]): string {
  const parts = mask.map((w) => (w === 0xffff ? '0xffff' : `0x${w.toString(16).padStart(4, '0')}`))
  return `[${parts.join(', ')}]`
}

/** the mask read back as text, so a reviewer can see what it matches */
function maskComment(mask: readonly number[]): string {
  return mask.map((w) => (w === 0xffff ? '??' : w >= 0x20 && w <= 0x7e ? String.fromCharCode(w) : `<${w.toString(16).padStart(2, '0')}>`)).join(' ')
}

const rows = found
  .map(
    (d) => `  {
    // ${maskComment(d.mask)}
    name: ${JSON.stringify(d.name)},
    baseName: ${JSON.stringify(d.baseName)},
    pattern: ${JSON.stringify(d.pattern)},
    groupID: ${JSON.stringify(d.groupID)},
    id: ${JSON.stringify(d.id)},
    flags: ${d.flags},
    priority: ${d.priority},
    mask: ${maskLiteral(d.mask)},
  },`,
  )
  .join('\n')

writeFileSync(
  'src/amiga/datatypes.gen.ts',
  `// GENERATED by src/cli/gendatatypes.ts from ${dir} — do not edit.
//
// The ${found.length} DataType descriptors a Workbench 3.0 Devs/DataTypes drawer holds,
// decoded from their IFF FORM DTYP files. Commodore's, and the Picture
// DataTypes package's; none of them is this port's. See ./datatypes.ts for
// the struct these fields come out of and for what the mask means.
//
// struct DataTypeHeader is ${DTHD.SIZEOF} bytes and every pointer in it is an offset from
// the start of the DTHD chunk, which is what makes a descriptor relocatable
// as a plain file.
import type { DataTypeHeader } from './datatypes'

export const SHIPPED_DATATYPES: readonly DataTypeHeader[] = [
${rows}
]
`,
)
console.log(`wrote src/amiga/datatypes.gen.ts (${found.length} descriptors)`)
for (const d of found) console.log(`  ${d.groupID}/${d.id.padEnd(8)} ${d.name}`)
