/**
 * Regenerate the registry table in docs/extensions/README.md.
 *
 * Run: npm run cli -- src/cli/genextdoc.ts
 *
 * The table used to be maintained by hand, and it drifted to listing 19 of 53
 * registered extensions — the failure mode of any hand-copied index. It reads
 * src/ext/tables.gen.ts rather than the manifests directly, so it works
 * without fixtures/ present: the generated tables are committed, the libraries
 * they came from are not.
 *
 * Prose about individual extensions stays hand-written below the table. This
 * generates the inventory, not the commentary — a row saying an extension is
 * `manual`-tier is a fact, "no manual found for *this* build" is a judgement.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { mdTable } from './mdtable'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { EXT_TABLES, EXT_INFO } from '../ext/tables.gen'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const doc = join(root, 'docs', 'extensions', 'README.md')

const BEGIN = '<!-- BEGIN registry (generated by src/cli/genextdoc.ts) -->'
const END = '<!-- END registry -->'

/** the evidence tiers, strongest first — the order docs/extensions ranks them */
const TIERS = ['source', 'disassembly', 'manual']
const tierRank = (t: string): number => {
  const i = TIERS.indexOf(t)
  return i < 0 ? TIERS.length : i
}

/**
 * Distinct named entries — which is what KEYWORDS.md counts, so the two
 * agree. A name can appear twice: IOPorts really does declare `serial speed`
 * at both $0048 and $0086, in Europress's own +IO_Ports.s, both pointing at
 * L_InSerialSpeed. Counting entries rather than names made this table say 39
 * where KEYWORDS.md said 38, and that gap had to be explained away every time
 * somebody compared them.
 */
const named = (id: string): number =>
  new Set((EXT_TABLES[id] ?? []).filter((t) => t.name).map((t) => t.name)).size

const rows = [...EXT_INFO]
  .sort(
    (a, b) =>
      tierRank(a.evidence) - tierRank(b.evidence) ||
      named(b.id) - named(a.id) ||
      a.id.localeCompare(b.id),
  )
  .map((e) => {
    const slots = e.observedSlots.length > 0 ? e.observedSlots.join(', ') : '—'
    // the binary's own word first, because it is the only one of the three
    // that nobody chose after the fact
    const where =
      e.statedSlot !== undefined
        ? `states ${e.statedSlot}`
        : e.origin === 'stock'
          ? `stock, slot ${e.defaultSlot}`
          : e.defaultSlot
            ? `recommends ${e.defaultSlot}`
            : '—'
    return [`\`${e.id}\``, e.name, e.evidence, String(named(e.id)), slots, where]
  })

const table = [
  BEGIN,
  '',
  `${EXT_INFO.length} extensions are registered, ${EXT_INFO.filter((e) => e.origin === 'stock').length} of them stock.`,
  'Ordered by evidence tier, then by size. "Keywords" counts DISTINCT named table',
  'entries, matching `KEYWORDS.md`: unnamed entries are argument-count and',
  'function-form variants of the keyword above them, and a name can legitimately',
  'appear twice (IOPorts declares `serial speed` at two ids). "Seen at" is the',
  "slots corpus programs actually used it in, which is evidence; \"Slot\" is where",
  'it belongs. Three kinds of answer, strongest first: "states N" is the',
  'library\'s own word — `d2` at its extension-call-1025 sites is the extension',
  'number, compiled in by whoever built it, and 62 rows carry one. "stock, slot',
  'N" is +Interpreter_Config.s. "recommends N" is a manual or a wiki page, which',
  'is a claim and not evidence. Eleven of the 62 have nothing but the binary.',
  '',
  '"Evidence" is what is available to read, not what has been read — see the tier',
  'rule above. Nearly every row says `source` or `disassembly` because a held',
  'binary outranks any manual, so the column separates the extensions whose',
  'behaviour is knowable from the ones where a port would be guessing. It says',
  'nothing about how much of each is ported; `src/cli/extaudit.ts` answers that,',
  'per keyword.',
  '',
  mdTable(['id', 'name', 'evidence', 'keywords', 'seen at', 'slot'], rows),
  '',
  END,
].join('\n')

const src = readFileSync(doc, 'utf8')
const from = src.indexOf(BEGIN)
const to = src.indexOf(END)
if (from < 0 || to < 0) {
  throw new Error(`${doc}: markers not found — expected ${BEGIN} ... ${END}`)
}
writeFileSync(doc, src.slice(0, from) + table + src.slice(to + END.length))
console.log(`docs/extensions/README.md: registry table written, ${rows.length} extensions`)
