/**
 * Generate src/runtime/edres.gen.ts — the AMOS Pro editor's resource bank.
 *
 * `Ed_ResourceLoad` (+Edit.s:4738) loads `AMOSPro_Editor_Resource.Abk` off
 * disk and checks it is a resource bank (`cmp.l #"Reso",-8(a0)`), so unlike
 * the mouse bank this is not something the machine carries inside itself.
 * It is baked in anyway because there is no editor here to load it, and
 * everything the editor draws comes out of it: the AMOS logo, the twelve
 * editor buttons and thirteen escape-screen ones, the memory sliders and the
 * window borders. `src/loader/resource.ts` already decodes the format.
 *
 * The whole bank, not the escape screen's share of it, so the editor has its
 * pictures waiting when it arrives.
 *
 * LICENCE: the bank is part of the official AMOS Professional source release,
 * which Francois Lionet published under the MIT licence in 2020 (its LICENSE
 * file carries "Copyright (c) 1992 Europress Software" and "Copyright (c)
 * 2020 Francois Lionet"). The README adds one condition to bare MIT: "you can
 * do anything you want from it as long as the copyright notice is present in
 * both the modified source code and the boot screen of the application". The
 * notice is in the generated file, and the escape screen prints it.
 *
 *   npx tsx src/cli/genedres.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const rel = 'AMOS/APSystem/AMOSPro_Editor_Resource.Abk'
const bytes = readFileSync(join(root, rel))
const b64 = bytes.toString('base64')
const lines = (b64.match(/.{1,96}/g) ?? []).map((l) => `  '${l}',`).join('\n')

writeFileSync(
  'src/runtime/edres.gen.ts',
  `// GENERATED by src/cli/genedres.ts from ${rel} — do not edit.
//
// The AMOS Professional editor's resource bank: every picture the editor and
// its escape screen draw. Ed_ResourceLoad (+Edit.s:4738) loads it from disk
// and Ed_Unpack (:13876) walks its graphics section, which is the ordinary
// "Reso" layout src/loader/resource.ts decodes.
//
// Copyright (c) 1992 Europress Software
// Copyright (c) 2020 Francois Lionet
// Published under the MIT licence as part of the official AMOS Professional
// source release. Its README asks that the copyright notice appear in both
// the modified source and the application's boot screen; ./directscreen.ts
// prints it on the escape screen.
const B64 = [
${lines}
].join('')

/** the raw AmBk file, ${bytes.length} bytes */
export const EDITOR_RESOURCE_BANK: Uint8Array = Uint8Array.from(atob(B64), (c) => c.charCodeAt(0))

/**
 * Picture numbers, as the editor names them (+Edit.s:106-113). Each is the
 * first of a run: a button is two pictures, up then down.
 */
export const ED_PICS = {
  /** Ed_Pics: the editor's own logo and window furniture */
  logo: 1,
  /** Ed_BtPics: the three window buttons, 2 each */
  windowButtons: 5,
  /** Ed_BoutonsPics: the twelve editor buttons, 2 each */
  editorButtons: 11,
  /** Ed_MemoryPics: the three memory-slider pictures */
  memory: 35,
  /** Es_Pics: the escape screen's logo, right border and bottom bar */
  escape: 38,
  /** Es_BoutonsPics: the thirteen escape-screen buttons, 2 each */
  escapeButtons: 41,
} as const
`,
)
console.log(`wrote src/runtime/edres.gen.ts (${bytes.length} bytes, ${b64.length} base64 chars)`)
