/**
 * Generate src/tokens/equates.gen.ts from AMOS Professional's own equates
 * file, which the Test pass reads and pokes values out of.
 *
 * `Equ_Load` (+Verif.s:1402) opens system message 9 through `Sys_AddPath`.
 * Equates.Doc names the result: "AMOSPro_Tutorial:AMOSPro_System_Equates".
 * The whole file is read into one buffer and searched with `L_InstrFind`
 * (+Lib.s:13829), a byte-exact substring search, for the key
 * "\n" + prefix + name + ":". The leading newline is why the file's first
 * byte is a newline and why the first entry can be found at all.
 *
 * The text is stored VERBATIM rather than parsed into a table, because the
 * search is over bytes and two of its results depend on that: the file names
 * `AEdAsk_X` twice so the second is unreachable, and line 21 reads
 * "AEd_WordRight:8,,7" where the second comma makes `Equ("AEd_WordRight")`
 * error 53 rather than return 8. A parsed table would quietly fix both.
 *
 *   npx tsx src/cli/genequates.ts [path-to-AMOSProfessional]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const path = join(root, 'AMOS/Productivity1/Equates/AMOSPro_System_Equates')
const text = readFileSync(path, 'latin1')

if (text.charCodeAt(0) !== 10) throw new Error('the file must open with a newline, or nothing matches')
if (/[^\x20-\x7e\n]/.test(text)) throw new Error('non-ASCII byte: the template literal below would not round-trip')
if (text.includes('`') || text.includes('${')) throw new Error('a backtick or ${ needs escaping')

const entries = text.split('\n').filter((l) => l.length > 0).length
const out = `// GENERATED by src/cli/genequates.ts from AMOS/Productivity1/Equates/AMOSPro_System_Equates — do not edit.
//
// The file the Test pass searches for \`Equ\`, \`Lvo\`, \`Struc\` and \`Struc$\`,
// held as text because \`Equ_Verif\` (+Verif.s:1308) searches it as text. See
// src/cli/genequates.ts for why that matters.
//
// ${entries} lines. Each is NAME:value,type, where type 0-2 is a signed byte,
// word or long, 3-5 the unsigned three, 6 a pointer to an AMOS string, and 7
// a plain equate that \`Struc\` refuses (\`cmp.b #7,d2 / bcc EquType\`, :1266).
//
// Copyright (c) 1992 Europress Software
// Copyright (c) 2020 Francois Lionet
// Published under the MIT licence as part of the official AMOS Professional
// source release.
export const SYSTEM_EQUATES = \`${text}\`
`
writeFileSync('src/tokens/equates.gen.ts', out)
console.log(`${entries} equates, ${text.length} bytes`)
