/**
 * Generate src/runtime/edmessages.gen.ts — the editor's five message
 * tables, straight out of +Editor_Config.s.
 *
 * `Resource$(n)` reaches these for n below -1000 (FnResource +ILib.s:6699):
 * -1001.. Ed_Systeme, -2001.. EdM_Messages, -3001.. Ed_Messages,
 * -4001.. Ed_TstMessages, -5001.. Ed_RunMessages, and -6001 and beyond is
 * a function call error.
 *
 * Each block is a run of records {pad byte, length byte, bytes}, walked
 * 1-based by GetMessage (+B.s:590) which skips the leading pad and stops
 * at a length of $FF. The EdT/EdD macros (+Editor_Config.s:37-47) emit
 * exactly that, so parsing the macro calls in order reproduces the block:
 * the number in the macro call is a comment, not an index — .Error1 starts
 * its numbering at 0, so a run-time error code is one behind its record.
 *
 * The menu block is `IncBin "bin/Editor_Menus.asc"`, a prebuilt file in
 * the same record format, so it is read as bytes rather than parsed.
 *
 *   npx tsx src/cli/genedmsg.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const src = readFileSync(join(root, '+Editor_Config.s'), 'latin1').split('\n')

/** the byte list of an EdD body: `dc.b 27,"B4",25` */
function assembleBytes(body: string): number[] {
  const out: number[] = []
  const text = body.replace(/^\s*dc\.b\s*/i, '')
  let i = 0
  while (i < text.length) {
    const c = text[i]!
    if (c === ',' || c === ' ' || c === '\t') {
      i++
      continue
    }
    if (c === '"') {
      i++
      while (i < text.length && text[i] !== '"') out.push(text.charCodeAt(i++))
      i++
      continue
    }
    let tok = ''
    while (i < text.length && text[i] !== ',') tok += text[i++]
    tok = tok.trim()
    if (tok === '') continue
    out.push(tok.startsWith('$') ? parseInt(tok.slice(1), 16) : Number(tok) & 0xff)
  }
  return out
}

/** every message between two labels, in order */
function block(from: string, to: string): string[] {
  const start = src.findIndex((l) => l.startsWith(from))
  const end = src.findIndex((l, i) => i > start && l.startsWith(to))
  if (start < 0 || end < 0) throw new Error(`block ${from}..${to} not found`)
  const out: string[] = []
  for (let i = start; i < end; i++) {
    const line = src[i]!
    const m = /\b(EdT|EdD)\s+-?\d+\s*,\s*<([\s\S]*)>\s*$/.exec(line)
    if (!m) {
      // a bare `dc.b 0,$FF` terminates the block early (Ed_Systeme, Ed_Messages)
      if (/dc\.b\s+0\s*,\s*\$[fF][fF]/.test(line)) break
      continue
    }
    out.push(
      m[1] === 'EdT'
        ? m[2]!
        : assembleBytes(m[2]!)
            .map((b) => String.fromCharCode(b))
            .join(''),
    )
  }
  return out
}

/** the prebuilt menu block: {pad, len, bytes} records, $FF ends it */
function fromBinary(path: string): string[] {
  const b = readFileSync(join(root, path))
  const out: string[] = []
  let p = 1 // GetMessage skips the leading pad byte
  while (p < b.length) {
    const len = b[p]!
    if (len === 0xff) break
    out.push(Buffer.from(b.subarray(p + 1, p + 1 + len)).toString('latin1'))
    p += 2 + len
  }
  return out
}

const tables = {
  ED_SYSTEME: block('.Sys1', '.Sys2'),
  EDM_MESSAGES: fromBinary('bin/Editor_Menus.asc'),
  ED_MESSAGES: block('Ed1', 'Ed2'),
  ED_TST_MESSAGES: block('.Test1', '.Test2'),
  ED_RUN_MESSAGES: block('.Error1', '.Error2'),
}

const lit = (s: string): string =>
  `'${[...s]
    .map((c) => {
      const n = c.charCodeAt(0)
      if (c === "'" || c === '\\') return '\\' + c
      if (n < 32 || n > 126) return '\\x' + n.toString(16).padStart(2, '0')
      return c
    })
    .join('')}'`

const head = `/**
 * GENERATED by src/cli/genedmsg.ts from +Editor_Config.s — do not edit.
 *
 * The editor's five message tables, the ones Resource$ reaches below
 * -1000 (FnResource +ILib.s:6699). Records are 1-based in the order the
 * block declares them (GetMessage +B.s:590); the numbers in the assembler
 * macro calls are comments and do not all start at 1.
 */
`

const body = Object.entries(tables)
  .map(
    ([name, msgs]) =>
      `\n/** ${msgs.length} messages */\nexport const ${name}: readonly string[] = [\n${msgs.map((m) => `  ${lit(m)},`).join('\n')}\n]\n`,
  )
  .join('')

writeFileSync('src/runtime/edmessages.gen.ts', head + body)
for (const [name, msgs] of Object.entries(tables)) console.log(`${name}: ${msgs.length}`)
