/**
 * Generate src/runtime/font.gen.ts from a PSF1 console font (8x8).
 *
 * AMOS rendered text with the Kickstart ROM's Topaz font, which we can't
 * ship; Lat15-VGA8 is a public 8x8 font with full Latin-1 coverage and a
 * close visual match.
 *
 *   npm run cli -- src/cli/genfont.ts [/usr/share/consolefonts/Lat15-VGA8.psf.gz]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'

const path = process.argv[2] ?? '/usr/share/consolefonts/Lat15-VGA8.psf.gz'
let bytes = readFileSync(path)
if (path.endsWith('.gz')) bytes = gunzipSync(bytes)

if (bytes[0] !== 0x36 || bytes[1] !== 0x04) throw new Error('not a PSF1 font')
const mode = bytes[2]!
const charSize = bytes[3]!
if (charSize !== 8) throw new Error(`want 8x8, got 8x${charSize}`)
const nGlyphs = mode & 0x01 ? 512 : 256
const hasTable = (mode & 0x06) !== 0

const glyphs: Uint8Array[] = []
for (let i = 0; i < nGlyphs; i++) {
  glyphs.push(bytes.subarray(4 + i * charSize, 4 + (i + 1) * charSize))
}

// map Latin-1 code points onto glyphs via the unicode table
const font: Uint8Array[] = Array.from({ length: 256 }, () => new Uint8Array(8))
if (hasTable) {
  let p = 4 + nGlyphs * charSize
  for (let i = 0; i < nGlyphs && p < bytes.length; i++) {
    for (;;) {
      const u = bytes.readUInt16LE(p)
      p += 2
      if (u === 0xffff) break
      if (u === 0xfffe) {
        // combining sequences follow — skip to terminator
        while (bytes.readUInt16LE(p) !== 0xffff) p += 2
        p += 2
        break
      }
      if (u < 256) font[u] = glyphs[i]!
    }
  }
} else {
  for (let i = 0; i < 256; i++) font[i] = glyphs[i]!
}

const rows: string[] = []
for (let c = 0; c < 256; c++) {
  const g = font[c]!
  const hex = [...g].map((b) => b.toString(16).padStart(2, '0')).join('')
  const ch = c >= 32 && c !== 127 ? ` // ${String.fromCharCode(c)}` : ''
  rows.push(`  '${hex}',${ch}`)
}

const out = `// GENERATED by src/cli/genfont.ts from ${path.split('/').pop()} — do not edit.
// 8x8 glyphs indexed by Latin-1 code point; each row is one byte, MSB = leftmost pixel.
const HEX: string[] = [
${rows.join('\n')}
]

export const FONT8: Uint8Array[] = HEX.map((h) => {
  const g = new Uint8Array(8)
  for (let i = 0; i < 8; i++) g[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16)
  return g
})
`
writeFileSync('src/runtime/font.gen.ts', out)
console.log(`wrote src/runtime/font.gen.ts (${rows.length} glyphs)`)
