/**
 * Extract JD's collation table from the author's source into a generated
 * constant.
 *
 * `Jd Crypt$` maps each byte to its POSITION in a 256-byte permutation, and
 * `Jd Encrypt$` maps each byte b to table[b] — the same table read the other
 * way, which is why the two are inverses. The table is what makes the manual's
 * "for german sorting" true: it lists 0, '|', tab, space, the digits, then the
 * letters in pairs with the umlauts interleaved (aA aeAE bB ... oO oeOE ...
 * sS ss ... uU ueUE), so sorting the crypted strings gives German dictionary
 * order rather than ASCII order.
 *
 * It is data, not an algorithm, so it is copied rather than derived.
 *
 * Run: npm run cli -- src/cli/genjdcrypt.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'

const SRC = 'fixtures/extensions/jd-5.3/jd.s.unpacked'
const OUT = 'src/runtime/jd-crypt.gen.ts'

const lines = readFileSync(SRC, 'latin1').split('\n')
const start = lines.findIndex((l) => l.startsWith('y:'))
const end = lines.findIndex((l) => l.startsWith('yend:'))
if (start < 0 || end < 0 || end <= start) {
  console.error(`could not find the y..yend table in ${SRC} — is it the unpacked source?`)
  process.exit(1)
}

const table: number[] = []
for (const line of lines.slice(start, end)) {
  const body = line.split('dc.b')[1]
  if (body === undefined) continue
  // quoted runs are literal bytes; everything else is a decimal value
  for (const part of body.match(/"(?:[^"]*)"|[^,]+/g) ?? []) {
    const p = part.trim()
    if (p === '') continue
    if (p.startsWith('"')) for (const c of p.slice(1, -1)) table.push(c.charCodeAt(0))
    else table.push(Number(p))
  }
}

if (table.length !== 256 || new Set(table).size !== 256) {
  console.error(`table is ${table.length} bytes with ${new Set(table).size} distinct — expected a 256-byte permutation`)
  process.exit(1)
}

const rows: string[] = []
for (let i = 0; i < 256; i += 16) rows.push('  ' + table.slice(i, i + 16).join(', ') + ',')
writeFileSync(
  OUT,
  `// GENERATED by src/cli/genjdcrypt.ts — do not edit.
//
// JD's collation table (\`y\`, +|jd.s:604-612). A 256-byte permutation:
// Jd Crypt\$ answers each byte's INDEX here, Jd Encrypt\$ answers the byte AT
// that index, so the two are inverses. The order is German dictionary order —
// digits, then letters in pairs with the umlauts interleaved next to the
// vowels they belong with, then punctuation — which is what makes crypting a
// string before sorting it sort German text correctly.

export const JD_CRYPT: readonly number[] = [
${rows.join('\n')}
]
`,
  'utf8',
)
console.log(`${OUT} written: ${table.length} bytes`)
