/**
 * Generate src/runtime/mousebank.gen.ts — the default mouse bank.
 *
 * T_MouBank is not a file the interpreter loads: +W.s:16795 links
 * bin/+AMOSPro_Mouse.abk straight into the interpreter binary, so every
 * AMOS machine has it. It holds the three pointer shapes (arrow,
 * crosshair, clock) and, from image 5 on, the Set Pattern / Set Slider
 * system fill patterns that SPat (+W.s:4701) indexes past the first four.
 *
 * 1824 bytes, so it is baked in as base64 rather than shipped as an asset.
 *
 *   npx tsx src/cli/genmouse.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const bytes = readFileSync(join(root, 'bin/+AMOSPro_Mouse.abk'))
const b64 = bytes.toString('base64')
const lines = (b64.match(/.{1,96}/g) ?? []).map((l) => `  '${l}',`).join('\n')

writeFileSync(
  'src/runtime/mousebank.gen.ts',
  `// GENERATED by src/cli/genmouse.ts from bin/+AMOSPro_Mouse.abk — do not edit.
// The mouse bank the interpreter carries inside itself (+W.s:16795):
// pointer shapes 1-3 and the system fill patterns from image 5 on.
const B64 = [
${lines}
].join('')

/** the raw AmBk file, ${bytes.length} bytes */
export const DEFAULT_MOUSE_BANK: Uint8Array = Uint8Array.from(atob(B64), (c) => c.charCodeAt(0))
`,
)
console.log(`wrote src/runtime/mousebank.gen.ts (${bytes.length} bytes)`)
