/**
 * Generate src/runtime/piconfig.gen.ts — the interpreter configuration
 * defaults, straight out of +Interpreter_Config.s.
 *
 * AMOS keeps a block of tunables at a5 (`PI_*`, declared +Equ.s:1590-1650)
 * which the editor's Interpreter Config screen edits and saves back into the
 * AMOSPro binary. They are ordinary defaults, not constants: the file
 * selector writes its Sort/Size/Store toggles and its window position back
 * into them when it closes (Fs_Close +Lib.s:18469-18483), so they persist
 * across calls within a session.
 *
 * The data block runs from `Dat1` to `Dat2`. Every line is a `dc.b`/`dc.w`/
 * `dc.l` with an optional `PI_` label, or a `ds.b`/`ds.l` reservation for the
 * unnamed padding; values are decimal, `$`hex, or a small product/sum
 * (`1024*32`, `129+48`). Most lines carry the field's byte offset in their
 * comment, so the generator recomputes offsets as it walks and asserts they
 * agree — a transcription error shows up as a build failure rather than a
 * wrong default.
 *
 *   npx tsx src/cli/genpiconfig.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const lines = readFileSync(join(root, '+Interpreter_Config.s'), 'latin1').split('\n')

/** `1024*32`, `129+48`, `$00404161`, `68` — sums of products, hex or decimal */
function value(expr: string): number {
  let total = 0
  for (const term of expr.split('+')) {
    let product = 1
    for (const factor of term.split('*')) {
      const t = factor.trim()
      product *= t.startsWith('$') ? parseInt(t.slice(1), 16) : parseInt(t, 10)
    }
    total += product
  }
  return total | 0
}

const WIDTH: Record<string, number> = { b: 1, w: 2, l: 4 }

interface Field {
  name: string
  offset: number
  width: number
  values: number[]
}

const fields: Field[] = []
const problems: string[] = []
let offset = 0
let started = false
/** the field a continuation line (no label, same directive) extends */
let last: Field | null = null

for (const raw of lines) {
  const line = raw.replace(/\r$/, '')
  if (!started) {
    if (/^Dat1\b/.test(line)) started = true
    continue
  }
  if (/^Dat2\b/.test(line)) break
  if (/^\s*;/.test(line) || line.trim() === '') continue

  // label? directive? operand? trailing comment (with or without a '*')
  //
  // The comment marker and the multiply sign are the same character, and
  // telling them apart is what the operand group does: a '*' with a non-space
  // on both sides is an operator, and one with whitespace before it starts
  // the comment. Excluding '*' outright read `dc.w 42*6` as 42, which put
  // PI_TVDirect, PI_VNmMax and PI_DefSize into the defaults at a fraction of
  // their value. The offset walk could not catch it: a dc.l is four bytes
  // whatever number is in it.
  const m = /^(\w*)\s+(dc|ds)\.([bwl])\s+((?:[^*;]|(?<=\S)\*(?=\S))*?)(?:\s+[*;].*)?$/i.exec(line)
  if (!m) continue
  const [, label, kind, size, operand] = m
  const width = WIDTH[size!.toLowerCase()]!

  if (kind!.toLowerCase() === 'ds') {
    offset += value(operand!) * width // unnamed reserved padding
    last = null
    continue
  }

  const values = operand!
    .split(',')
    .map((v) => v.trim())
    .filter((v) => v !== '')
    .map(value)

  if (label) {
    // the comment usually opens with the field's own byte offset
    const stated = /[*;]\s*(\d+)\s*-/.exec(line)
    if (stated && Number(stated[1]) !== offset) {
      problems.push(`${label}: source comment says offset ${stated[1]}, walked to ${offset}`)
    }
    const field: Field = { name: label.replace(/^PI_/, ''), offset, width, values }
    fields.push(field)
    last = field
  } else if (last && last.width === width && last.values.length > 1) {
    // a continuation of a genuine list (the 32-entry default palette), not
    // the unnamed single-value filler that also sits between named fields
    last.values.push(...values)
  } else {
    last = null // unnamed filler between named fields
  }
  offset += values.length * width
}

if (problems.length) {
  console.error('offset mismatches:\n  ' + problems.join('\n  '))
  process.exit(1)
}
if (fields.length === 0) throw new Error('no PI_ fields found — did the source layout change?')

const scalars = fields.filter((f) => f.values.length === 1)
const arrays = fields.filter((f) => f.values.length > 1)

const out: string[] = []
out.push('// GENERATED by src/cli/genpiconfig.ts — do not edit.')
out.push('// Source: +Interpreter_Config.s (defaults) / +Equ.s:1590-1650 (layout).')
out.push('')
out.push('/**')
out.push(' * The interpreter configuration block AMOS keeps at a5. These are the')
out.push(' * editor-editable defaults, and some are written back at run time —')
out.push(' * Fs_Close (+Lib.s:18469) stores the file selector\'s toggles and window')
out.push(' * position here, so they survive from one Fsel$ to the next.')
out.push(' *')
out.push(' * Field names are the AMOS ones with the PI_ prefix dropped, and the')
out.push(' * comment on each is its byte offset in the original block.')
out.push(' */')
out.push('export interface PiConfig {')
for (const f of scalars) out.push(`  /** +${f.offset} */`, `  ${f.name}: number`)
for (const f of arrays) out.push(`  /** +${f.offset}, ${f.values.length} entries */`, `  ${f.name}: number[]`)
out.push('}')
out.push('')
out.push('export const PI_DEFAULTS: PiConfig = {')
for (const f of scalars) out.push(`  ${f.name}: ${f.values[0]},`)
for (const f of arrays) out.push(`  ${f.name}: [${f.values.join(', ')}],`)
out.push('}')
out.push('')
out.push('/** a fresh mutable copy — the running interpreter edits its own */')
out.push('export const newPiConfig = (): PiConfig => ({')
out.push('  ...PI_DEFAULTS,')
for (const f of arrays) out.push(`  ${f.name}: [...PI_DEFAULTS.${f.name}],`)
out.push('})')
out.push('')

writeFileSync('src/runtime/piconfig.gen.ts', out.join('\n'))
console.log(
  `src/runtime/piconfig.gen.ts written: ${fields.length} fields (${scalars.length} scalar, ${arrays.length} array), block is ${offset} bytes`,
)
