/**
 * Generate src/runtime/personnal-trig.gen.ts — the three fixed-point trig
 * tables Personnal's Fc Cos/Fc Sin/Fc Tan read.
 *
 * The extension declares them as raw includes (+AMOSPro_Personnal.Lib.s:514):
 *
 *   _Cosinus   IncBin "_TABLES/_CosTable.Bin"
 *   _Sinus     IncBin "_TABLES/_SinTable.Bin"
 *   _Tangente  IncBin "_TABLES/_TanTable.Bin"
 *
 * Each is 360 big-endian signed longwords, one per whole degree, holding the
 * function scaled by 1000. The keywords do nothing but normalise the angle
 * and index the table, so the values ARE the specification.
 *
 * They cannot be recomputed. `Math.trunc(fn(deg) * 1000)` reproduces all but
 * ten entries: sin(150) is 500 against the table's 499, cos(300) the mirror
 * of it, and seven around tan's poles — the difference between whatever
 * computed these in 1992 and IEEE double. Both tan(90) and tan(270) are
 * $7FFFFFFF, positive infinity in both directions.
 *
 *   npx tsx src/cli/genptrig.ts [path-to-AMOS-Professional-Official]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = process.argv[2] ?? '../AMOS-Professional-Official'
const dir = join(root, 'extensions', 'Personal-1.1a', '_TABLES')

const read = (file: string): number[] => {
  const b = readFileSync(join(dir, file))
  if (b.length !== 360 * 4) throw new Error(`${file}: expected 1440 bytes, got ${b.length}`)
  return Array.from({ length: 360 }, (_, i) => b.readInt32BE(i * 4))
}

const cos = read('_CosTable.bin')
const sin = read('_SinTable.bin')
const tan = read('_TanTable.bin')

// a transcription check that would fail loudly on the wrong file
for (const [name, t, expect] of [
  ['cos', cos, [1000, 0, -1000, 0]],
  ['sin', sin, [0, 1000, 0, -1000]],
  ['tan', tan, [0, 0x7fffffff, 0, 0x7fffffff]],
] as Array<[string, number[], number[]]>) {
  const got = [t[0], t[90], t[180], t[270]]
  if (got.some((v, i) => v !== expect[i])) throw new Error(`${name}: quadrants are ${got.join(',')}`)
}

const fmt = (t: number[]): string => {
  const lines: string[] = []
  for (let i = 0; i < 360; i += 12) lines.push('  ' + t.slice(i, i + 12).join(', ') + ',')
  return lines.join('\n')
}

const out = `// GENERATED by src/cli/genptrig.ts — do not edit.
//
// Personnal's Fc Cos / Fc Sin / Fc Tan tables (_TABLES/_{Cos,Sin,Tan}Table.Bin,
// included at +AMOSPro_Personnal.Lib.s:514). 360 entries each, one per whole
// degree, holding the function scaled by 1000. Not recomputable: ten entries
// differ from Math.trunc(fn(deg) * 1000). Both tan poles are $7FFFFFFF.

export const P_COS: readonly number[] = [
${fmt(cos)}
]

export const P_SIN: readonly number[] = [
${fmt(sin)}
]

export const P_TAN: readonly number[] = [
${fmt(tan)}
]
`
writeFileSync('src/runtime/personnal-trig.gen.ts', out)
console.log(`wrote src/runtime/personnal-trig.gen.ts — 3 x 360 entries`)
