/**
 * Generate src/tokens/tables.gen.ts from the compiled AMOS Pro libraries in
 * fixtures/. Run: npm run cli -- src/cli/gentable.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseAmosLib, parseAmosLibOld } from '../tokens/libtok'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const sys = join(root, 'fixtures', 'official-amos', 'APSystem')

/**
 * The core interpreter libraries only. Extensions — stock and third-party
 * alike — are generated by src/cli/genext.ts into src/ext/tables.gen.ts,
 * keyed by extension identity rather than by slot, because a slot number
 * identifies nothing on its own (see docs/extensions/README.md).
 */
/**
 * The AGA release's own core library used to be generated alongside this one as
 * AGA_CORE_TOKENS. It was dropped because the two tables came out BYTE
 * IDENTICAL: the AGA build of AMOS Pro ships the same core token table, so a
 * second copy bought nothing but ~780 generated lines. scan.ts had been
 * retrying failed parses against it, which could never succeed for the same
 * reason.
 *
 * That is a finding worth keeping rather than just a deletion: if a future AGA
 * or 1.3-era library DOES differ, add it back here and the difference will show
 * up as a table that is not identical.
 */
const LIBS: Array<{ slot: number; file: string; label: string; dir?: string; old?: boolean }> = [
  { slot: 0, file: 'AMOSPro.Lib', label: 'core' },
]

let out = `// GENERATED by src/cli/gentable.ts from the AMOS Pro 2.00 libraries — do not edit.
// Token id = byte offset of the entry in the library's token table.
export interface TokenDef {
  id: number
  name: string
  spec: string
  instr: number
  func: number
}

`
for (const { file, label, dir, old } of LIBS) {
  const raw = readFileSync(join(dir ?? sys, file))
  const lib = old ? parseAmosLibOld(raw) : parseAmosLib(raw)
  console.log(`${file}: ${lib.tokens.length} tokens`)
  const constName = `${label.toUpperCase()}_TOKENS`
  out += `export const ${constName}: TokenDef[] = [\n`
  for (const t of lib.tokens) {
    out += `  { id: 0x${t.id.toString(16).padStart(4, '0')}, name: ${JSON.stringify(t.name)}, spec: ${JSON.stringify(t.spec)}, instr: 0x${t.instr.toString(16)}, func: 0x${t.func.toString(16)} },\n`
  }
  out += `]\n\n`
}
writeFileSync(join(root, 'src', 'tokens', 'tables.gen.ts'), out)
console.log('wrote src/tokens/tables.gen.ts')
