/**
 * Generate src/tokens/tables.gen.ts from the compiled AMOS Pro libraries in
 * fixtures/. Run: npm run cli -- src/cli/gentable.ts
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseAmosLib, parseAmosLibOld } from '../tokens/libtok'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const sys = join(root, 'fixtures', 'official-amos', 'APSystem')

/** extension slot number -> library file, per +Interpreter_Config.s (entry 14 = slot 0 = core) */
const agaSys = join(root, 'fixtures', 'aga-releases', 'APSystemAGA')
const extDir = join(root, 'fixtures', 'extensions')
const LIBS: Array<{ slot: number; file: string; label: string; dir?: string; old?: boolean }> = [
  { slot: 0, file: 'AMOSPro.Lib', label: 'core' },
  { slot: -1, file: 'AmosProAGA.Lib', label: 'aga_core', dir: agaSys },
  { slot: 1, file: 'AMOSPro_Music.Lib', label: 'music' },
  { slot: 2, file: 'AMOSPro_Compact.Lib', label: 'compact' },
  { slot: 3, file: 'AMOSPro_Request.Lib', label: 'request' },
  { slot: 5, file: 'AMOSPro_Compiler.Lib', label: 'compiler' },
  { slot: 6, file: 'AMOSPro_IOPorts.Lib', label: 'ioports' },
  // third-party extensions on the user's machine (non-AP20 format); the
  // slots are the ext numbers the corpus's tokenised files reference
  { slot: 10, file: 'AMOSPro_Ldos.lib', label: 'ldos', dir: extDir, old: true },
  { slot: 12, file: 'AMOSPro_TURBO_Plus.Lib', label: 'turbo', dir: extDir, old: true },
  { slot: 24, file: 'amospro_gui.lib', label: 'gui', dir: extDir, old: true },
]

let out = `// GENERATED by src/cli/gentable.ts from the AMOS Pro 2.00 libraries — do not edit.
// Token id = byte offset of the entry in the library's token table.
export interface TokenDef {
  id: number
  name: string
  spec: string
  instr: number
  func: number
}

`
const slotEntries: string[] = []
for (const { slot, file, label, dir, old } of LIBS) {
  const raw = readFileSync(join(dir ?? sys, file))
  const lib = old ? parseAmosLibOld(raw) : parseAmosLib(raw)
  console.log(`${file}: ${lib.tokens.length} tokens`)
  const constName = `${label.toUpperCase()}_TOKENS`
  out += `export const ${constName}: TokenDef[] = [\n`
  for (const t of lib.tokens) {
    out += `  { id: 0x${t.id.toString(16).padStart(4, '0')}, name: ${JSON.stringify(t.name)}, spec: ${JSON.stringify(t.spec)}, instr: 0x${t.instr.toString(16)}, func: 0x${t.func.toString(16)} },\n`
  }
  out += `]\n\n`
  if (slot > 0) slotEntries.push(`  [${slot}, ${constName}],`)
}
out += `/** extension slot number -> token defs, per the default interpreter config */
export const EXTENSION_TOKENS = new Map<number, TokenDef[]>([
${slotEntries.join('\n')}
])
`
writeFileSync(join(root, 'src', 'tokens', 'tables.gen.ts'), out)
console.log('wrote src/tokens/tables.gen.ts')
