/**
 * Generate src/tokens/verif.gen.ts — the verifier's class per core token.
 *
 * `Ver_Ech` (+Verif.s:5231) walks the loaded token table and SWAPS each
 * entry's two routine words for a four-byte record held in the library's
 * `LB_Verif` table. So for the length of a verification the first long of
 * every entry is not a pair of routine numbers, and `VerDd` (:250) can pick
 * a handler with one indexed read:
 *
 *     move.l  AdTokens(a5),a0
 *     move.b  0(a0,d0.w),d1        the instruction class
 *     move.b  1(a0,d0.w),d1        the operand class, at Ope_Loop (:2589)
 *     move.b  2(a0),d0             the spec offset, at Ver_DInst (:3179)
 *
 * The shipped table is `AMOSPro Sources/+Toktab_Verif.Bin`, 3,112 bytes for
 * 778 entries. It is not written by hand: `c/Make_Toktable.AMOS` reads +Lib.s
 * between its `TOKEN_START` and `TOKEN_END` comments and turns every
 * `//$XX$XX$XX$XX` annotation into four bytes. That is the source this reads,
 * and running it against a copy of the .Bin reproduces it exactly, 3,112 for
 * 3,112.
 *
 * The fourth byte is not read anywhere in +Verif.s. 723 of the 778 are zero
 * and the rest sit on the control-flow keywords, so it is dropped here rather
 * than shipped as data nothing consumes.
 *
 * LICENCE: +Lib.s is part of the official AMOS Professional source release,
 * MIT-licensed by Francois Lionet in 2020. See src/cli/genedres.ts.
 *
 * The default root is the corpus copy, which is the one every `+Verif.s:NNNN`
 * in this port resolves against. `../AMOS-Professional-Official` is a second
 * revision of the same release, 5,321 lines of +Verif.s against 5,294, and
 * its token annotations are identical to the byte.
 *
 *   npx tsx src/cli/genverif.ts [path-to-the-AMOS-Pro-sources]
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { CORE_TOKENS } from '../tokens/tables.gen'

const root = process.argv[2] ?? '../amos-files/sources/aminet-dev-amos/files/AMOSProfessional/AMOSProfessional'
const src = readFileSync(join(root, '+Lib.s'), 'latin1')
const from = src.indexOf('TOKEN_START')
const to = src.indexOf('TOKEN_END')
if (from < 0 || to < 0) throw new Error('+Lib.s has no TOKEN_START/TOKEN_END pair')

const rows = [...src.slice(from, to).matchAll(/\/\/\$(\w\w)\$(\w\w)\$(\w\w)\$(\w\w)/g)].map((m) =>
  m.slice(1).map((h) => parseInt(h, 16)),
)
if (rows.length !== CORE_TOKENS.length) {
  throw new Error(`${rows.length} annotations for ${CORE_TOKENS.length} tokens`)
}

// Ver_DInst reaches the spec with byte 2 alone, so byte 2 has to be the four
// routine/verif bytes plus the name, and a nameless entry's name is one $80.
for (let i = 0; i < rows.length; i++) {
  const want = 4 + Math.max(1, CORE_TOKENS[i]!.name.length)
  if (rows[i]![2] !== want) {
    throw new Error(`entry ${i} (${CORE_TOKENS[i]!.name}): spec offset ${rows[i]![2]}, expected ${want}`)
  }
}

let out = `// GENERATED by src/cli/genverif.ts from +Lib.s — do not edit.
//
// The class the verifier dispatches on, one row per core token, in the same
// order and with the same ids as CORE_TOKENS. \`inst\` picks the handler in
// VerDd's jump table (+Verif.s:291), \`ope\` the one in Ope_Loop's (:2602).
//
// Copyright (c) 1992 Europress Software
// Copyright (c) 2020 Francois Lionet
// Published under the MIT licence as part of the official AMOS Professional
// source release.
export interface VerifDef {
  id: number
  inst: number
  ope: number
}

export const VERIF_CLASSES: VerifDef[] = [
`
for (let i = 0; i < rows.length; i++) {
  const t = CORE_TOKENS[i]!
  const [inst, ope] = rows[i]!
  const h = (n: number): string => `0x${n.toString(16).padStart(2, '0')}`
  const note = t.name === '' ? '' : ` // ${t.name}`
  out += `  { id: 0x${t.id.toString(16).padStart(4, '0')}, inst: ${h(inst!)}, ope: ${h(ope!)} },${note}\n`
}
out += ']\n'
writeFileSync('src/tokens/verif.gen.ts', out)
console.log(`wrote src/tokens/verif.gen.ts: ${rows.length} tokens`)
