// GENERATED by src/cli/gendatatypes.ts from ../amos-files/sources/amos-pd-library-cd-1994/files/Devs/DataTypes — do not edit.
//
// The 10 DataType descriptors a Workbench 3.0 Devs/DataTypes drawer holds,
// decoded from their IFF FORM DTYP files. Commodore's, and the Picture
// DataTypes package's; none of them is this port's. See ./datatypes.ts for
// the struct these fields come out of and for what the mask means.
//
// struct DataTypeHeader is 32 bytes and every pointer in it is an offset from
// the start of the DTHD chunk, which is what makes a descriptor relocatable
// as a plain file.
import type { DataTypeHeader } from './datatypes'

export const SHIPPED_DATATYPES: readonly DataTypeHeader[] = [
  {
    // F O R M ?? ?? ?? ?? 8 S V X
    name: "8SVX",
    baseName: "8svx",
    pattern: "#?",
    groupID: "soun",
    id: "8svx",
    flags: 2,
    priority: 0,
    mask: [0x0046, 0x004f, 0x0052, 0x004d, 0xffff, 0xffff, 0xffff, 0xffff, 0x0038, 0x0053, 0x0056, 0x0058],
  },
  {
    // @ d a t a b a s e
    name: "AmigaGuide",
    baseName: "amigaguide",
    pattern: "#?",
    groupID: "docu",
    id: "amig",
    flags: 1,
    priority: 0,
    mask: [0x0040, 0x0064, 0x0061, 0x0074, 0x0061, 0x0062, 0x0061, 0x0073, 0x0065],
  },
  {
    // F O R M ?? ?? ?? ?? F T X T
    name: "FTXT",
    baseName: "ascii",
    pattern: "#?",
    groupID: "text",
    id: "ftxt",
    flags: 2,
    priority: 0,
    mask: [0x0046, 0x004f, 0x0052, 0x004d, 0xffff, 0xffff, 0xffff, 0xffff, 0x0046, 0x0054, 0x0058, 0x0054],
  },
  {
    // G I F 8 ?? a
    name: "GIF",
    baseName: "gif",
    pattern: "#?",
    groupID: "pict",
    id: "gif\u0000",
    flags: 0,
    priority: 0,
    mask: [0x0047, 0x0049, 0x0046, 0x0038, 0xffff, 0x0061],
  },
  {
    // F O R M ?? ?? ?? ?? I L B M
    name: "ILBM",
    baseName: "ilbm",
    pattern: "#?",
    groupID: "pict",
    id: "ilbm",
    flags: 2,
    priority: 0,
    mask: [0x0046, 0x004f, 0x0052, 0x004d, 0xffff, 0xffff, 0xffff, 0xffff, 0x0049, 0x004c, 0x0042, 0x004d],
  },
  {
    // <ff> <d8> <ff> <e0> ?? ?? J F I F
    name: "JPEG",
    baseName: "jpeg",
    pattern: "#?",
    groupID: "pict",
    id: "jpeg",
    flags: 0,
    priority: 0,
    mask: [0x00ff, 0x00d8, 0x00ff, 0x00e0, 0xffff, 0xffff, 0x004a, 0x0046, 0x0049, 0x0046],
  },
  {
    // <00>
    name: "MacPaint",
    baseName: "macpaint",
    pattern: "#?",
    groupID: "pict",
    id: "macp",
    flags: 0,
    priority: 0,
    mask: [0x0000],
  },
  {
    // <0a> ?? <01>
    name: "Zsoft PCX",
    baseName: "pcx",
    pattern: "#?.pcx",
    groupID: "pict",
    id: "zsof",
    flags: 0,
    priority: 0,
    mask: [0x000a, 0xffff, 0x0001],
  },
  {
    // B M
    name: "Windows Bitmap",
    baseName: "bmp",
    pattern: "#?.BMP",
    groupID: "pict",
    id: "wind",
    flags: 0,
    priority: 0,
    mask: [0x0042, 0x004d],
  },
  {
    // <00> <00> <01> <00> <01> <00>
    name: "Windows Icon",
    baseName: "ico",
    pattern: "#?.ico",
    groupID: "pict",
    id: "wind",
    flags: 0,
    priority: 0,
    mask: [0x0000, 0x0000, 0x0001, 0x0000, 0x0001, 0x0000],
  },
]
