/**
 * GENERATED by src/cli/gendecrunch.ts — do not edit.
 *
 * DecrunchLib 35.237 (20.2.93) - LICENCEWARE © 1992,1993 by Georg Hörmann
 *
 * The identification tables behind Explode's `Dpk Name$` and `Dpk Unpack`,
 * extracted from the library's own code hunk. 16 data magics, 76 executable
 * signatures, and one format found by scanning. See the generator for what
 * each stage is and why the order matters, and ./decrunchlib.ts for the walk.
 *
 * LICENCEWARE. The library is not redistributed; this is the DATA a format is
 * recognised by, and the name the library gives it.
 */

/** the library's own version string, checked by ./decrunchlib.corpus.test.ts */
export const DL_ID_STRING = 'DecrunchLib 35.237 (20.2.93) - LICENCEWARE © 1992,1993 by Georg Hörmann\r\n'

/**
 * Stage one: the first longword of a DATA file, tested in this order.
 *
 * Every one of these carries subid 2, which is what `dlDecrunch` tests at
 * $1066 to take the data path. `width: 2` is the one WORD test, and `also`
 * the one entry that needs a second longword to match.
 */
export interface DlDataMagic {
  /** the value compared — a longword unless `width` says otherwise */
  readonly magic: number
  readonly width: 2 | 4
  /** a second longword that must also match, at this offset */
  readonly also?: { readonly at: number; readonly value: number }
  readonly id: number
  readonly subId: number
  readonly name: string
}

export const DL_DATA_MAGICS: readonly DlDataMagic[] = [
  { magic: 0x542e5320, width: 4, also: { at: 4, value: 0x322e3030 }, id: 0x59, subId: 2, name: 'TurtleSmasher 2.00 D' },
  { magic: 0x50503230, width: 4, id: 0x48, subId: 2, name: 'PowerPacker D' },
  { magic: 0x50583230, width: 4, id: 0x49, subId: 2, name: 'PowerPacker D/E' },
  { magic: 0x53333030, width: 4, id: 0x4a, subId: 2, name: 'StoneCracker 3.00 D' },
  { magic: 0x53333130, width: 4, id: 0x4b, subId: 2, name: 'StoneCracker 3.10 D' },
  { magic: 0x53343030, width: 4, id: 0x4c, subId: 2, name: 'StoneCracker 4.00 D' },
  { magic: 0x53343031, width: 4, id: 0x4d, subId: 2, name: 'StoneCracker 4.01 D' },
  { magic: 0x49434521, width: 4, id: 0x56, subId: 2, name: 'IAM Packer 1.0 D (ICE!)' },
  { magic: 0x41544d35, width: 4, id: 0x55, subId: 2, name: 'IAM Packer 1.0 D (ATM5)' },
  { magic: 0x5041434b, width: 4, id: 0x57, subId: 2, name: 'SoundTracker Song' },
  { magic: 0x43724d21, width: 4, id: 0x4e, subId: 2, name: 'CrunchMania D' },
  { magic: 0x43726d21, width: 4, id: 0x5a, subId: 2, name: 'CrunchMania D/S' },
  { magic: 0x43724d32, width: 4, id: 0x5b, subId: 2, name: 'CrunchMania D/H' },
  { magic: 0x43726d32, width: 4, id: 0x5c, subId: 2, name: 'CrunchMania D/H/S' },
  { magic: 0x5049636f, width: 4, id: 0x50, subId: 2, name: 'PackIt 1.0 D' },
  { magic: 0x4248, width: 2, id: 0x51, subId: 2, name: 'DragPack 2.52 D' },
]

/**
 * Stage two: three (offset, longword) probes that must ALL match, applied
 * after any hunk header has been stepped over. Tried in table order.
 */
export interface DlSignature {
  readonly probes: readonly (readonly [number, number])[]
  readonly id: number
  readonly subId: number
  readonly name: string
}

export const DL_SIGNATURES: readonly DlSignature[] = [
  { probes: [[176, 0x303cffff], [198, 0x44fc0010], [206, 0x53414242]], id: 0x18, subId: 1, name: 'Black&Decker 2.0' },
  { probes: [[4, 0x4df900df], [10, 0x41fa00ba], [136, 0x14b22000]], id: 0x19, subId: 1, name: 'ByteKiller 2.0' },
  { probes: [[14, 0x4df900df], [160, 0x44c7e290], [178, 0xe290e392]], id: 0x1a, subId: 1, name: 'ByteKiller 3.0' },
  { probes: [[4, 0x1c3c6e6f], [14, 0x41fa00dc], [38, 0x2a280008]], id: 0x3c, subId: 1, name: 'ByteKiller Pro 1.0' },
  { probes: [[4, 0x1c3c736b], [56, 0x41fa00d4], [26, 0x50f900bf]], id: 0x3d, subId: 1, name: 'ByteKiller Pro 1.0 K' },
  { probes: [[26, 0x43724d2e], [30, 0x6c696272], [34, 0x61727900]], id: 0x5d, subId: 0, name: 'CrunchMania R/L/[H]' },
  { probes: [[12, 0x4e944e91], [16, 0x4e942449], [20, 0x52464e94]], id: 0x10, subId: 0, name: 'CrunchMania R/N/[H]' },
  { probes: [[8, 0x221a241a], [12, 0x224a287a], [20, 0xd9cc2a49]], id: 0x11, subId: 0, name: 'CrunchMania R/S' },
  { probes: [[2, 0x45fa007a], [6, 0x41fa007e], [34, 0x0c505456]], id: 0x29, subId: 1, name: 'Crunch Master 1.0' },
  { probes: [[36, 0x45ea0100], [40, 0x41ea0100], [8, 0xd7cbd7cb]], id: 0x3f, subId: 0, name: 'Crunch-O-Matic 1.0 E' },
  { probes: [[4, 0xd9ccd9cc], [44, 0x22402440], [52, 0x49ec000a]], id: 0x40, subId: 1, name: 'Crunch-O-Matic 1.0 I/M/T' },
  { probes: [[340, 0x20444546], [344, 0x4a414d20], [6, 0x4bf900df]], id: 0x26, subId: 1, name: 'DefJam Cruncher 3.2' },
  { probes: [[106, 0x20444546], [110, 0x4a414d20], [0, 0x4df900df]], id: 0x27, subId: 1, name: 'DefJam Cruncher 3.2 Pro' },
  { probes: [[96, 0x446f7562], [128, 0x20545249], [104, 0x6374696f]], id: 0x3a, subId: 1, name: 'Double Action 1.0' },
  { probes: [[16, 0x20182218], [20, 0x2a182449], [24, 0xd1c0d5c1]], id: 0x0a, subId: 0, name: 'DragPack 1.0' },
  { probes: [[0, 0x487a0046], [8, 0x49faffee], [78, 0x342044c5]], id: 0x0b, subId: 0, name: 'DragPack 2.52' },
  { probes: [[42, 0x43f800c4], [52, 0x4ef800c4], [164, 0x12331000]], id: 0x4f, subId: 1, name: 'FCG 1.0' },
  { probes: [[14, 0x26497000], [22, 0x0c180001], [74, 0x41444550]], id: 0x1b, subId: 1, name: 'FlashSpeed 1.0' },
  { probes: [[96, 0x46726565], [100, 0x77615920], [112, 0x45544951]], id: 0x52, subId: 1, name: 'Freeway 0.7' },
  { probes: [[154, 0x1018e188], [158, 0x1018e188], [162, 0x1018e188]], id: 0x1c, subId: 1, name: 'High Pressure Cruncher' },
  { probes: [[24, 0x41fa0676], [30, 0x41fa0664], [34, 0x43fa0510]], id: 0x2a, subId: 0, name: 'HQC Cruncher 2.0' },
  { probes: [[0, 0x487a0172], [28, 0x61000158], [380, 0x41544d35]], id: 0x53, subId: 0, name: 'IAM Packer 1.0 (ATM5)' },
  { probes: [[0, 0x487a0172], [28, 0x61000158], [392, 0x49434521]], id: 0x54, subId: 0, name: 'IAM Packer 1.0 (ICE!)' },
  { probes: [[4, 0x49fa0036], [12, 0x612e4e91], [50, 0x2f49003c]], id: 0x03, subId: 0, name: 'Imploder 1.0-3.1' },
  { probes: [[4, 0x49fa0036], [12, 0x4e944e91], [50, 0x2f49003c]], id: 0x38, subId: 0, name: 'Imploder 1.0-3.1 P' },
  { probes: [[4, 0x49fa005e], [12, 0x61564e91], [20, 0x2f49003c]], id: 0x04, subId: 0, name: 'Imploder 4.0' },
  { probes: [[14, 0x4eaefdd8], [24, 0x4eaeffe2], [0, 0x48e7ffff]], id: 0x0f, subId: 0, name: 'Lib Imploded' },
  { probes: [[4, 0x4bfa0180], [20, 0x2b490014], [32, 0x610c4eb9]], id: 0x1e, subId: 1, name: 'Master Cruncher 3.0 A' },
  { probes: [[4, 0x4bfa0338], [22, 0x2b490014], [32, 0x2b4a0018]], id: 0x0c, subId: 0, name: 'Master Cruncher 3.0 R' },
  { probes: [[108, 0xd3016406], [126, 0xd301d100], [180, 0xd3016422]], id: 0x2b, subId: 1, name: 'MaxPacker 1.2' },
  { probes: [[0, 0x47fa012e], [10, 0x41fa0130], [282, 0x51c90008]], id: 0x33, subId: 1, name: 'Mega Cruncher 1.0' },
  { probes: [[0, 0x47fa0132], [10, 0x41fa0134], [286, 0x51c90008]], id: 0x36, subId: 1, name: 'Mega Cruncher 1.2 A' },
  { probes: [[124, 0x4d656761], [128, 0x20437275], [152, 0x616c6c6f]], id: 0x2c, subId: 0, name: 'Mega Cruncher 1.2 R' },
  { probes: [[8, 0x2e0e286e], [12, 0x01144bfa], [18, 0x42954aac]], id: 0x0d, subId: 0, name: 'PackIt 1.0' },
  { probes: [[242, 0x61646472], [60, 0x2c075386], [418, 0x10351000]], id: 0x01, subId: 0, name: 'PowerPacker 2.x' },
  { probes: [[0, 0x487a0178], [8, 0x49fafff2], [40, 0x20575148]], id: 0x02, subId: 0, name: 'PowerPacker 3.0' },
  { probes: [[0, 0x60164869], [8, 0x536e6f6f], [24, 0x487a0176]], id: 0x12, subId: 0, name: 'PP 3.0 Overlayed' },
  { probes: [[0, 0x487a01f6], [16, 0x45fa02a0], [32, 0xcb4e7e02]], id: 0x13, subId: 0, name: 'PP 3.0 Password' },
  { probes: [[0, 0x487a01c8], [8, 0x49fafff2], [40, 0x20575148]], id: 0x08, subId: 0, name: 'PowerPacker 4.0' },
  { probes: [[0, 0x487a0058], [8, 0x702343fa], [44, 0x4eaeffb2]], id: 0x09, subId: 0, name: 'PP 4.0 Library' },
  { probes: [[0, 0x60164869], [8, 0x536e6f6f], [24, 0x487a01c8]], id: 0x14, subId: 0, name: 'PP 4.0 Overlayed' },
  { probes: [[0, 0x60164869], [8, 0x536e6f6f], [24, 0x487a0058]], id: 0x15, subId: 0, name: 'PP 4.0 Overlay/Lib' },
  { probes: [[0, 0x487a0246], [16, 0x45fa02f0], [32, 0xcb4e7e02]], id: 0x16, subId: 0, name: 'PP 4.0 Password' },
  { probes: [[0, 0x487a005c], [8, 0x702343fa], [48, 0x4eaeffac]], id: 0x17, subId: 0, name: 'PP 4.0 Password/Lib' },
  { probes: [[4, 0x41fa02c6], [104, 0x22d88290], [348, 0x48814a01]], id: 0x2d, subId: 0, name: 'ReloKit 1.0' },
  { probes: [[6, 0x4eaeff6a], [24, 0x41fa00f6], [34, 0x47fa0016]], id: 0x1d, subId: 1, name: 'RSI Packer 1.4' },
  { probes: [[2, 0x5370696b], [6, 0x65312e31], [32, 0xd7cbd7cb]], id: 0x3e, subId: 0, name: 'Spike Cruncher 1.5' },
  { probes: [[236, 0x204d722e], [240, 0x20537069], [248, 0x20434156]], id: 0x2e, subId: 1, name: 'StoneCracker 2.70' },
  { probes: [[380, 0x204d722e], [384, 0x20537069], [392, 0x20434156]], id: 0x2f, subId: 1, name: 'StoneCracker 2.70 K' },
  { probes: [[92, 0x2076322e], [96, 0x39322062], [112, 0x20434156]], id: 0x47, subId: 1, name: 'StoneCracker 2.92' },
  { probes: [[92, 0x2e393920], [98, 0x4d722e53], [108, 0x43415645]], id: 0x30, subId: 1, name: 'StoneCracker 2.99' },
  { probes: [[90, 0x2e393920], [94, 0x4d722e53], [102, 0x43415645]], id: 0x3b, subId: 1, name: 'StoneCracker 2.99d' },
  { probes: [[92, 0x204d722e], [96, 0x53706976], [100, 0x2f434156]], id: 0x31, subId: 1, name: 'StoneCracker 3.00' },
  { probes: [[94, 0x204d722e], [98, 0x53706976], [102, 0x204f6620]], id: 0x32, subId: 1, name: 'StoneCracker 3.10' },
  { probes: [[90, 0x265a201a], [94, 0xd7c8224a], [100, 0x4eecfe78]], id: 0x39, subId: 1, name: 'StoneCracker 3.11' },
  { probes: [[42, 0x21c90010], [48, 0x2e4049fa], [54, 0x45fa00f0]], id: 0x42, subId: 1, name: 'StoneCracker 4.01 A' },
  { probes: [[42, 0x21c90010], [48, 0x2e4049f9], [66, 0x45fa00d0]], id: 0x43, subId: 1, name: 'StoneCracker 4.01ß A' },
  { probes: [[4, 0x4bfafff6], [76, 0x20954295], [94, 0x53006af6]], id: 0x44, subId: 0, name: 'StoneCracker 4.00' },
  { probes: [[4, 0x4bfafff6], [76, 0x20954295], [94, 0x51c8fff8]], id: 0x45, subId: 0, name: 'StoneCracker 4.01 C' },
  { probes: [[0, 0x41fa0166], [4, 0x22582018], [256, 0x47fa0007]], id: 0x34, subId: 1, name: 'SyncroPacker 4.6' },
  { probes: [[28, 0x21c80020], [64, 0x45fa0166], [68, 0x4ed141f9]], id: 0x28, subId: 1, name: 'SyncroPacker 4.6 K' },
  { probes: [[82, 0xb1b900df], [124, 0x49f80080], [134, 0x4ef80080]], id: 0x46, subId: 1, name: 'TetraPack 1.02' },
  { probes: [[172, 0x20544554], [176, 0x5241474f], [112, 0x153220ff]], id: 0x22, subId: 1, name: 'TetraPack 2.1' },
  { probes: [[96, 0x20544554], [100, 0x5241474f], [92, 0x4eea0040]], id: 0x23, subId: 1, name: 'TetraPack 2.1 Pro' },
  { probes: [[196, 0x20544554], [200, 0x5241474f], [118, 0x44fc0010]], id: 0x24, subId: 1, name: 'TetraPack 2.2' },
  { probes: [[138, 0x20544554], [142, 0x5241474f], [134, 0x4eeb0040]], id: 0x25, subId: 1, name: 'TetraPack 2.2 Pro' },
  { probes: [[0, 0x41fa0134], [16, 0x2460d5c9], [282, 0x44fc0010]], id: 0x20, subId: 1, name: 'TFA Cruncher 1.54' },
  { probes: [[104, 0x44fc0010], [108, 0xe290e393], [300, 0xe290e392]], id: 0x1f, subId: 1, name: 'Time Cruncher 1.7-2.2' },
  { probes: [[28, 0x074f7665], [40, 0x6c696272], [178, 0x76ff4ead]], id: 0x05, subId: 0, name: 'Titanics Cruncher 1.1' },
  { probes: [[24, 0x646f732e], [142, 0x4eaefe80], [146, 0x4eaefe8c]], id: 0x06, subId: 0, name: 'Titanics Cruncher 1.2' },
  { probes: [[26, 0xd1c8d1c8], [32, 0xd3c9d3c9], [36, 0x58885889]], id: 0x07, subId: 0, name: 'TNM Cruncher 1.1' },
  { probes: [[0, 0x43fa0598], [4, 0x2e29fffc], [8, 0x45fa0016]], id: 0x35, subId: 1, name: 'TryIt 1.01' },
  { probes: [[30, 0x2a280008], [34, 0x2005e588], [48, 0xd3e80004]], id: 0x0e, subId: 0, name: 'TurboSqueezer 8.0' },
  { probes: [[0, 0x41fa0148], [6, 0x45fa0114], [18, 0x41e8fff0]], id: 0x21, subId: 1, name: 'TurtleSmasher 1.3' },
  { probes: [[0, 0x43fa03f4], [8, 0x323c046c], [20, 0x45ea0020]], id: 0x58, subId: 1, name: 'TurtleSmasher 2.00' },
  { probes: [[4, 0x0000abcd], [32, 0x50535231], [46, 0x20af0040]], id: 0x37, subId: 0, name: 'Ultimate Packer 1.1b' },
]

/**
 * Stage three: the format with no signature, found by looking for three
 * instructions in sequence — `lead` within the first `leadTries` words of the
 * code, then `then` within the next `thenTries`, then `third` immediately.
 */
export const DL_SCAN = {
  lead: 0x45fa,
  leadTries: 101,
  then: 0x221a,
  thenTries: 21,
  third: 0x241a,
  id: 0x41,
  subId: 1,
  name: 'CrunchMania A',
} as const
