/**
 * GENERATED by src/cli/genlocale.ts — do not edit.
 *
 * AmigaOS locale.library data, extracted from the AROS sources
 * (workbench/libs/locale/english.c and defaultlocale.c, plus the string ids in
 * compiler/include/libraries/locale.h and localestd.h).
 *
 * AROS is a clean-room reimplementation of AmigaOS, licensed APL/LGPL. What is
 * reproduced here is data rather than code: the ISO-8859-1 case and collation
 * tables, the English names of the days and months, and the default locale's
 * date templates. The generator's header explains why that is the right
 * evidence for this and what it does not cover.
 *
 * Independently corroborated: the Locale structure field order these format
 * strings sit in is the one read out of AMOSPro_locale.lib itself, whose
 * `Date$` fetches +$4c — loc_DateFormat, the second of the six.
 */

/** MAXSTRMSG: GetLocaleStr ids run 1..51 */
export const MAXSTRMSG = 52

/** locale.library standard string ids (libraries/localestd.h, libraries/locale.h) */
export const STR_ID = {
  DAY_1: 1,
  DAY_2: 2,
  DAY_3: 3,
  DAY_4: 4,
  DAY_5: 5,
  DAY_6: 6,
  DAY_7: 7,
  ABDAY_1: 8,
  ABDAY_2: 9,
  ABDAY_3: 10,
  ABDAY_4: 11,
  ABDAY_5: 12,
  ABDAY_6: 13,
  ABDAY_7: 14,
  MON_1: 15,
  MON_2: 16,
  MON_3: 17,
  MON_4: 18,
  MON_5: 19,
  MON_6: 20,
  MON_7: 21,
  MON_8: 22,
  MON_9: 23,
  MON_10: 24,
  MON_11: 25,
  MON_12: 26,
  ABMON_1: 27,
  ABMON_2: 28,
  ABMON_3: 29,
  ABMON_4: 30,
  ABMON_5: 31,
  ABMON_6: 32,
  ABMON_7: 33,
  ABMON_8: 34,
  ABMON_9: 35,
  ABMON_10: 36,
  ABMON_11: 37,
  ABMON_12: 38,
  YESSTR: 39,
  NOSTR: 40,
  AM_STR: 41,
  PM_STR: 42,
  MS_ISO: 0,
  MS_AMERICAN: 1,
  MS_IMPERIAL: 2,
  MS_BRITISH: 3,
  CT_7SUN: 0,
  CT_7MON: 1,
  CT_7TUE: 2,
  CT_7WED: 3,
  CT_7THU: 4,
  CT_7FRI: 5,
  CT_7SAT: 6,
  SS_NOSPACE: 0,
  SS_SPACE: 1,
  SP_PARENS: 0,
  SP_PREC_ALL: 1,
  SP_SUCC_ALL: 2,
  SP_PREC_CURR: 3,
  SP_SUCC_CURR: 4,
  CSP_PRECEDES: 0,
  CSP_SUCCEEDS: 1,
  SC_ASCII: 0,
  SC_COLLATE1: 1,
  SC_COLLATE2: 2,
  SOFTHYPHEN: 43,
  HARDHYPHEN: 44,
  OPENQUOTE: 45,
  CLOSEQUOTE: 46,
  YESTERDAYSTR: 47,
  TODAYSTR: 48,
  TOMORROWSTR: 49,
  FUTURESTR: 50,
  LANG_NAME: 51,
} as const

/** english.language's strings, indexed by the ids above; [0] is the blank */
export const LANGUAGE_STRINGS: readonly string[] = [
  "",
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sun",
  "Mon",
  "Tue",
  "Wed",
  "Thu",
  "Fri",
  "Sat",
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
  "Yes",
  "No",
  "am",
  "pm",
  "­",
  "-",
  "\"",
  "\"",
  "Yesterday",
  "Today",
  "Tomorrow",
  "Future",
]

/** defLocale's six date templates, in loc_DateTimeFormat..loc_ShortTimeFormat order */
export const DEFAULT_FORMATS = {
  dateTime: "%A %B %e %Y %Q:%M %p",
  date: "%A %B %e",
  time: "%Q:%M:%S %p",
  shortDateTime: "%m/%d/%y %Q:%M %p",
  shortDate: "%m/%d/%y",
  shortTime: "%Q:%M %p",
} as const

/** ConvToLower: __code_table_to_lower */
export const TO_LOWER: readonly number[] = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
  64, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
  112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 91, 92, 93, 94, 95,
  96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
  112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
  128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
  144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
  160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
  176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
  224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
  240, 241, 242, 243, 244, 245, 246, 215, 248, 249, 250, 251, 252, 253, 254, 223,
  224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
  240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
]

/** ConvToUpper: __code_table_to_upper. StrnCmp uses this for SC_ASCII */
export const TO_UPPER: readonly number[] = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
  64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
  80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
  96, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
  80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 123, 124, 125, 126, 127,
  128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
  144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
  160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
  176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
  192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
  208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
  192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
  208, 209, 210, 211, 212, 213, 214, 247, 216, 217, 218, 219, 220, 221, 222, 255,
]

/** StrnCmp SC_COLLATE1: __language_short_order_tab */
export const SHORT_ORDER: readonly number[] = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
  64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
  80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
  96, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
  80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 97, 98, 99, 100, 101,
  224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
  240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
  32, 33, 36, 36, 103, 104, 105, 83, 106, 107, 108, 34, 109, 110, 111, 112,
  112, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 34, 124, 125, 126, 63,
  65, 65, 65, 65, 65, 65, 65, 67, 69, 69, 69, 69, 73, 73, 73, 73,
  68, 78, 79, 79, 79, 79, 79, 42, 79, 85, 85, 85, 85, 89, 84, 83,
  65, 65, 65, 65, 65, 65, 65, 67, 69, 69, 69, 69, 73, 73, 73, 73,
  68, 78, 79, 79, 79, 79, 79, 47, 79, 85, 85, 85, 85, 89, 84, 89,
]

/** StrnCmp SC_COLLATE2: __language_long_order_tab */
export const LONG_ORDER: readonly number[] = [
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15,
  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
  32, 34, 36, 39, 40, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53, 54,
  56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
  73, 74, 90, 92, 96, 100, 110, 112, 114, 116, 126, 128, 130, 132, 134, 138,
  152, 154, 156, 158, 162, 166, 176, 178, 180, 182, 187, 189, 190, 191, 192, 193,
  194, 75, 91, 93, 97, 101, 111, 113, 115, 117, 127, 129, 131, 133, 135, 139,
  153, 155, 157, 159, 163, 167, 177, 179, 181, 183, 188, 195, 196, 197, 198, 199,
  224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239,
  240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
  33, 35, 41, 42, 200, 201, 202, 160, 203, 204, 205, 37, 206, 207, 208, 209,
  210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 38, 221, 222, 223, 72,
  76, 77, 78, 79, 80, 81, 82, 94, 102, 103, 104, 105, 118, 119, 120, 121,
  98, 136, 140, 141, 142, 143, 144, 49, 145, 168, 169, 170, 171, 184, 164, 161,
  83, 84, 85, 86, 87, 88, 89, 95, 106, 107, 108, 109, 122, 123, 124, 125,
  99, 137, 146, 147, 148, 149, 150, 55, 151, 172, 173, 174, 175, 185, 165, 186,
]
