/**
 * The THX waveform bank — 63 filtered copies of 6,520 generated bytes.
 *
 * THX carries no PCM, so every sound it makes starts here: six triangles, six
 * sawtooths, thirty-two pulse widths and a noise table, generated by about
 * ninety instructions with no input at all. The replayer then runs a resonant
 * filter over the whole set thirty-one times at rising cutoffs, keeping both
 * the low-pass and the high-pass output, which is where an instrument's filter
 * sweep comes from.
 *
 * ## Evidence
 *
 * DISASSEMBLY tier, from `AMOSPro_Jotre.Lib`: the generator at $57c-$692, the
 * filter at $696-$76c, the pointer stores at $77c-$79c.
 *
 * Everything reconciles to the byte, and it is worth writing the sum out
 * because it is what makes the reading checkable:
 *
 *     $649f0 = 412,144 = the AllocMem
 *              1,384   = $568, the state block in front of the waveforms
 *            + 410,760 = 63 x 6,520
 *     $64488 = 410,760 = what InitPlayer reads from the cache file
 *
 * so the allocation, the file length and the set size are three statements of
 * one arithmetic and all three agree.
 *
 * ## thx-0.6 generates a DIFFERENT set, and this is not it
 *
 * The two builds share the shape and disagree on every size. thx-0.6's
 * generator TILES each waveform to a fixed 128 bytes — its triangle loop
 * carries `move.l #$80,d6 / divu.w d2,d6 / subq.w #$1,d6` and repeats the
 * 4-byte triangle thirty-two times — where Jotre's has no such loop and emits
 * one waveform of each size. Its squares are a single 256-byte pair and
 * Jotre's are thirty-two pulse widths; its noise is 4,736 bytes and Jotre's is
 * 1,920.
 *
 *     thx-0.6   768 + 768 + 256 + 4,736 = 6,528
 *     jotre     252 + 252 + 4,096 + 1,920 = 6,520
 *
 * Eight bytes apart by coincidence and not comparable otherwise. Jotre is the
 * reference here, so Jotre's is what this file builds.
 *
 * ## Nothing is transcribed
 *
 * The library carries 2,790 bytes of filter start values at $1738 and another
 * 2,790 at $221e, one word for each of the 31 filters times 45 waveforms, and
 * NONE of it is copied here. They are what the filter state reaches after
 * running over its waveform exactly three times from zero, which `thxFilter`
 * computes — see `filterStart`. All 1,395 pairs reproduce exactly, and
 * `thxwaves.test.ts` checks every one against the shipped library.
 *
 * That is also the strongest check this file has. Three hundred lines of
 * generator and filter arithmetic could be wrong in a hundred places and still
 * produce 6,520 bytes; agreeing with 1,395 independent 16-bit values out of
 * somebody else's binary is another matter.
 */

/** the 45 waveforms, in the order the generator writes them */
export const THX_TRIANGLE_SIZES: readonly number[] = [4, 8, 16, 32, 64, 128]
export const THX_SAWTOOTH_SIZES: readonly number[] = [4, 8, 16, 32, 64, 128]
/** thirty-two pulse widths, 128 bytes each */
export const THX_SQUARE_COUNT = 32
export const THX_SQUARE_BYTES = 128
export const THX_NOISE_BYTES = 1920

/** where each family starts in a set — `$556`, `$55a` and `$562(a6)` hold the first, second and fourth */
export const THX_OFF_TRIANGLES = 0
export const THX_OFF_SAWTOOTHS = 252
export const THX_OFF_SQUARES = 504
export const THX_OFF_NOISE = 4600

/** one set of every waveform, unfiltered */
export const THX_SET_BYTES = 6520

/** 31 low-pass sets, the unfiltered one, then 31 high-pass — `$568`, `$31af0`, `$33468` */
export const THX_FILTER_COUNT = 31
export const THX_BANK_SETS = 63
export const THX_BANK_BYTES = THX_BANK_SETS * THX_SET_BYTES

/**
 * The filter coefficient, `move.l #$19,d5` then `addi.l #$9,d5` a filter.
 *
 * 25 to 295 in steps of nine, which is the whole of the cutoff range an
 * instrument's filter bytes can select.
 */
export const thxFilterCoefficient = (filter: number): number => 25 + 9 * filter

/**
 * The lengths the filter walks a set in, from the 45 words at `$3c2`.
 *
 * Stored there as length MINUS ONE, for the `dbra`. Not read out of the
 * library: the same numbers fall out of the generator above, and
 * `thxwaves.test.ts` holds them to the shipped table.
 */
export function thxGroups(): number[] {
  return [
    ...THX_TRIANGLE_SIZES,
    ...THX_SAWTOOTH_SIZES,
    ...Array.from({ length: THX_SQUARE_COUNT }, () => THX_SQUARE_BYTES),
    THX_NOISE_BYTES,
  ]
}

/** signed 8-bit, the way every `move.b` into the set lands */
const sb = (v: number): number => (v << 24) >> 24

/**
 * One triangle, the subroutine at `$41c`.
 *
 * Four pieces: a rising ramp of `n/4` bytes, a single $7f, a falling ramp of
 * `n/4 - 1`, then the whole lot MIRRORED and negated by reading back over what
 * was just written — `lea (a1,d4.w),a2` with d4 = -(n/2) is the read pointer,
 * and `$7f` becomes `$80` rather than being negated because negating $7f in a
 * byte gives $81.
 */
function triangle(out: number[], n: number): void {
  const quarter = n >> 2
  const step = Math.floor(128 / quarter)
  const start = out.length
  let v = 0
  for (let i = 0; i < quarter; i++) {
    out.push(sb(v))
    v = (v + step) & 0xffff
  }
  out.push(0x7f)
  let d = 0x80
  for (let i = 0; i < quarter - 1; i++) {
    d = (d - step) & 0xffff
    out.push(sb(d))
  }
  // `move.b (a2)+,(a1) / cmpi.b #$7f,(a1) / beq -> #$80 / else neg.b (a1)+`
  let read = out.length - (n >> 1)
  for (let i = 0; i < n >> 1; i++) {
    const b = out[read++]! & 0xff
    out.push(b === 0x7f ? -128 : sb(-b))
  }
  if (out.length - start !== n) throw new Error(`THX triangle ${String(n)} came out ${String(out.length - start)}`)
}

/**
 * The noise generator at `$656-$692`, seeded `$41595321`.
 *
 * A byte a pass, and the branch is the interesting part: when bit 8 of the
 * state is set the output SATURATES to $7f or $80 on the sign of bit 15
 * instead of taking the low byte, so about half the table is hard rails rather
 * than uniform noise. That is what makes it sound like a C64 rather than like
 * white noise.
 */
function noise(out: number[], count: number): void {
  let d0 = 0x41595321 | 0
  for (let i = 0; i < count; i++) {
    if ((d0 >>> 8) & 1) out.push((d0 & 0x8000) !== 0 ? -128 : 0x7f)
    else out.push(sb(d0 & 0xff))
    // ror.l #$5 / eori.b #$9a / rol.l #$2 on a word copy / add.w / eor.w / ror.l #$3
    d0 = ((d0 >>> 5) | (d0 << 27)) | 0
    d0 = (d0 & ~0xff) | ((d0 ^ 0x9a) & 0xff)
    let d1 = d0 & 0xffff
    d0 = ((d0 << 2) | (d0 >>> 30)) | 0
    d1 = (d1 + (d0 & 0xffff)) & 0xffff
    d0 = (d0 & ~0xffff) | ((d0 ^ d1) & 0xffff)
    d0 = ((d0 >>> 3) | (d0 << 29)) | 0
  }
}

/**
 * The unfiltered set — `$57c-$692`, 6,520 bytes.
 *
 * The sawtooth steps are `floor(255 / (n - 1))`: $55, $24, $11, 8, 4, 2 for
 * the six lengths, which walks -128 up to as near 127 as a byte add gets.
 *
 * The squares are the family THX is named for. Pulse `n` of 32 is
 * `(64 - n) * 2` bytes of -128 then `n * 2` of $7f, so the duty cycle runs
 * 1/64 to 32/64 and every one of them is 128 bytes.
 */
export function thxWaveSet(): Int8Array {
  const out: number[] = []
  for (const n of THX_TRIANGLE_SIZES) triangle(out, n)
  for (const n of THX_SAWTOOTH_SIZES) {
    const step = Math.floor(255 / (n - 1))
    let v = 0x80
    for (let i = 0; i < n; i++) {
      out.push(sb(v))
      v = (v + step) & 0xff
    }
  }
  for (let width = 1; width <= THX_SQUARE_COUNT; width++) {
    for (let i = 0; i < (0x40 - width) * 2; i++) out.push(-128)
    for (let i = 0; i < width * 2; i++) out.push(0x7f)
  }
  noise(out, THX_NOISE_BYTES)
  if (out.length !== THX_SET_BYTES) throw new Error(`THX wave set came out ${String(out.length)}`)
  return Int8Array.from(out)
}

/** `cmpi.w #$7f / ble / move.l #$7f` and its negative twin, on the high word */
const clampHigh = (v: number): number => (v > 0x7f ? 0x7f : v < -0x80 ? -0x80 : v)

interface FilterState {
  /** d2 — the band-pass integrator, 24.8 */
  a: number
  /** d3 — the low-pass one */
  b: number
}

/**
 * One waveform through the filter, `$6da-$754`.
 *
 * A two-pole state variable filter in 24.8 fixed point, and both taps are
 * kept: `(sample << 16) - a - b` is the high-pass and `b` is the low-pass.
 * Each integrator is clamped to a byte after its update, so the thing
 * distorts rather than blowing up.
 *
 * `hp` and `lp` are optional because the warm-up runs this three times for the
 * state alone and has nowhere to put the output.
 */
function filterPass(
  src: Int8Array,
  at: number,
  len: number,
  coeff: number,
  st: FilterState,
  hp?: Int8Array,
  lp?: Int8Array,
  out = 0,
): void {
  let { a, b } = st
  for (let i = 0; i < len; i++) {
    const s = (src[at + i]! << 16) | 0
    let d1 = (s - a - b) | 0
    const h = d1 >> 16
    // the clamp is `move.l #$7f,d1`, which replaces the WHOLE long --- so a
    // clamped sample feeds a clean 24.8 value back into the integrator
    if (h > 0x7f) d1 = 0x7f << 16
    else if (h < -0x80) d1 = -0x80 << 16
    if (hp) hp[out + i] = clampHigh(h)
    a = (a + Math.imul(d1 >> 8, coeff)) | 0
    const ha = a >> 16
    if (ha > 0x7f) a = 0x7f << 16
    else if (ha < -0x80) a = -0x80 << 16
    b = (b + Math.imul(a >> 8, coeff)) | 0
    const hb = b >> 16
    if (hb > 0x7f) b = 0x7f << 16
    else if (hb < -0x80) b = -0x80 << 16
    if (lp) lp[out + i] = clampHigh(hb)
  }
  st.a = a
  st.b = b
}

/** how many warm-up passes the shipped start values correspond to */
const WARMUP_PASSES = 3

/**
 * The start values the library ships at `$1738` and `$221e`, computed.
 *
 * Run the filter over the waveform three times from zero and take the top word
 * of each integrator. All 1,395 pairs come out equal to the shipped ones,
 * which is why none of those 5,580 bytes is in this tree.
 *
 * Three is not an obvious number and nothing in the code explains it — it is
 * few enough to still be moving (the state carries on drifting to a different
 * place by pass fifty) and enough to look settled. Whatever the author's
 * reason, three is what the tables are, and this reproduces them rather than
 * arguing with them.
 *
 * The `>> 8` and the reload are lossy on purpose: the library stores a WORD
 * and the filter reloads it with `ext.l / asl.l #$8`, so the low eight bits of
 * the warmed state are thrown away. Reproducing that matters, because the
 * output differs if it is not.
 */
export function filterStart(set: Int8Array, at: number, len: number, coeff: number): FilterState {
  const st: FilterState = { a: 0, b: 0 }
  for (let p = 0; p < WARMUP_PASSES; p++) filterPass(set, at, len, coeff, st)
  // `move.w (a4)+,d2 / ext.l d2 / asl.l #$8,d2`
  return { a: (st.a >> 8) << 8, b: (st.b >> 8) << 8 }
}

/** the two words the library holds for one filter and one waveform */
export const thxFilterStartWords = (set: Int8Array, at: number, len: number, coeff: number): [number, number] => {
  const st: FilterState = { a: 0, b: 0 }
  for (let p = 0; p < WARMUP_PASSES; p++) filterPass(set, at, len, coeff, st)
  return [st.a >> 8, st.b >> 8]
}

/**
 * The whole bank, laid out as the allocation is: 31 low-pass sets, the
 * unfiltered set, then 31 high-pass sets.
 *
 * The coefficient rises with the filter index and both destinations grow
 * upward, so set 0 is the LOWEST cutoff and therefore the darkest: measured on
 * the noise table, the mean sample-to-sample step is 2 at set 0, 71 at set 30
 * and 116 dry. The high-pass end runs the other way, 108 at set 32 up to 148
 * at set 62, because a high-pass with a very low cutoff passes nearly
 * everything.
 */
export function thxFilterBank(): Uint8Array {
  const set = thxWaveSet()
  const groups = thxGroups()
  const bank = new Uint8Array(THX_BANK_BYTES)
  const dry = THX_FILTER_COUNT * THX_SET_BYTES
  bank.set(new Uint8Array(set.buffer, set.byteOffset, set.length), dry)

  const hp = new Int8Array(THX_SET_BYTES)
  const lp = new Int8Array(THX_SET_BYTES)
  for (let f = 0; f < THX_FILTER_COUNT; f++) {
    const coeff = thxFilterCoefficient(f)
    let at = 0
    for (const len of groups) {
      const st = filterStart(set, at, len, coeff)
      filterPass(set, at, len, coeff, st, hp, lp, at)
      at += len
    }
    bank.set(new Uint8Array(lp.buffer, lp.byteOffset, lp.length), f * THX_SET_BYTES)
    bank.set(new Uint8Array(hp.buffer, hp.byteOffset, hp.length), dry + THX_SET_BYTES + f * THX_SET_BYTES)
  }
  return bank
}

/**
 * The seventeen words at `$1716` that the sine table is built from, and the
 * table itself.
 *
 * `$7a0-$7d4` copies them forward into `$3be(a6)`, then walks BACK over
 * fifteen of them, which gives a 32-word half period; the second half is
 * written through a second pointer at `$3fe(a6)` — exactly 64 bytes further on
 * — and then negated in place by `neg.w (a1)+` thirty-two times. One table,
 * two pointers, and the negate loop lands on what the second pointer wrote.
 *
 * The seeds are held rather than computed: they are `round(sin(x) * 255)` at
 * 16 steps of a quarter turn to within a unit, and "to within a unit" is not
 * a reproduction. `thxwaves.test.ts` pins them to both libraries.
 */
export const THX_SINE_SEEDS: readonly number[] = [
  0, 24, 49, 74, 97, 120, 141, 161, 180, 197, 212, 224, 235, 244, 250, 253, 255,
]

export function thxSine(): Int16Array {
  const half: number[] = [...THX_SINE_SEEDS]
  for (let i = 15; i >= 1; i--) half.push(THX_SINE_SEEDS[i]!)
  return Int16Array.from([...half, ...half.map((v) => -v)])
}
